# Form implementation generated from reading ui file 'student_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StudentDashboard(object):
    def setupUi(self, StudentDashboard):
        StudentDashboard.setObjectName("StudentDashboard")
        StudentDashboard.resize(1100, 650)
        StudentDashboard.setMinimumSize(QtCore.QSize(1000, 600))
        StudentDashboard.setStyleSheet("QMainWindow { background-color: #f5f7fa; }")
        self.centralwidget = QtWidgets.QWidget(parent=StudentDashboard)
        self.centralwidget.setStyleSheet("background-color: #f5f7fa;")
        self.centralwidget.setObjectName("centralwidget")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHorizontalLayout.setSpacing(0)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.sidebarFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebarFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.sidebarFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sidebarFrame.setStyleSheet("QFrame { background-color: white; }")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarLayout.setSpacing(0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.headerWidget = QtWidgets.QWidget(parent=self.sidebarFrame)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 210))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.headerWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,   /* start color */\n"
"        stop: 1 #764BA2    /* end color */\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}\n"
"")
        self.headerWidget.setObjectName("headerWidget")
        self.headerLayout = QtWidgets.QVBoxLayout(self.headerWidget)
        self.headerLayout.setContentsMargins(25, 32, 25, 28)
        self.headerLayout.setSpacing(20)
        self.headerLayout.setObjectName("headerLayout")
        self.logoHLayout = QtWidgets.QHBoxLayout()
        self.logoHLayout.setObjectName("logoHLayout")
        self.logoIconLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoIconLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setStyleSheet("background-color: white; border-radius: 15px; font-size: 34px;")
        self.logoIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIconLabel.setObjectName("logoIconLabel")
        self.logoHLayout.addWidget(self.logoIconLabel)
        self.logoTextLayout = QtWidgets.QVBoxLayout()
        self.logoTextLayout.setSpacing(4)
        self.logoTextLayout.setObjectName("logoTextLayout")
        self.labelLogoTitle = QtWidgets.QLabel(parent=self.headerWidget)
        self.labelLogoTitle.setStyleSheet("color: white; font-size: 23px; font-weight: 800; background: transparent;")
        self.labelLogoTitle.setObjectName("labelLogoTitle")
        self.logoTextLayout.addWidget(self.labelLogoTitle)
        self.labelLogoSubtitle = QtWidgets.QLabel(parent=self.headerWidget)
        self.labelLogoSubtitle.setStyleSheet("color: rgba(255,255,255,0.95); font-size: 13px; background: transparent;")
        self.labelLogoSubtitle.setObjectName("labelLogoSubtitle")
        self.logoTextLayout.addWidget(self.labelLogoSubtitle)
        self.logoHLayout.addLayout(self.logoTextLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoHLayout.addItem(spacerItem)
        self.headerLayout.addLayout(self.logoHLayout)
        self.profileFrame = QtWidgets.QFrame(parent=self.headerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileFrame.sizePolicy().hasHeightForWidth())
        self.profileFrame.setSizePolicy(sizePolicy)
        self.profileFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.profileFrame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255,255,255,0.22);\n"
"    border-radius: 15px;\n"
"    border: 1px solid rgba(255,255,255,0.35);\n"
"}")
        self.profileFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profileFrame)
        self.gridLayout.setContentsMargins(-1, 5, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelStudentName = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelStudentName.setMinimumSize(QtCore.QSize(20, 20))
        self.labelStudentName.setStyleSheet("color: white; \n"
"font-size: 17px; \n"
"font-weight: 800;\n"
"background: transparent;\n"
"border: transparent")
        self.labelStudentName.setObjectName("labelStudentName")
        self.verticalLayout.addWidget(self.labelStudentName)
        self.labelStudentRole = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelStudentRole.setMinimumSize(QtCore.QSize(0, 20))
        self.labelStudentRole.setStyleSheet("color: rgba(255,255,255,0.88); \n"
"font-size: 13px; \n"
"font-weight: 500;\n"
"background: transparent;\n"
"border: transparent")
        self.labelStudentRole.setObjectName("labelStudentRole")
        self.verticalLayout.addWidget(self.labelStudentRole)
        self.labelStudentStatus = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelStudentStatus.setMinimumSize(QtCore.QSize(0, 20))
        self.labelStudentStatus.setStyleSheet("color: rgba(255,255,255,0.95); \n"
"font-size: 11px; \n"
"font-weight: 600;\n"
"border: transparent;\n"
"background-color: transparent")
        self.labelStudentStatus.setObjectName("labelStudentStatus")
        self.verticalLayout.addWidget(self.labelStudentStatus)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.avatarLabel = QtWidgets.QLabel(parent=self.profileFrame)
        self.avatarLabel.setMinimumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setMaximumSize(QtCore.QSize(60, 60))
        self.avatarLabel.setStyleSheet("background-color: white;\n"
"color: #5a4fff;   /* vibrant purple-blue */\n"
"border-radius: 30px;\n"
"font-size: 26px;\n"
"font-weight: 900;\n"
"")
        self.avatarLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.avatarLabel.setObjectName("avatarLabel")
        self.gridLayout.addWidget(self.avatarLabel, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.headerLayout.addWidget(self.profileFrame)
        self.sidebarLayout.addWidget(self.headerWidget)
        self.navScrollArea = QtWidgets.QScrollArea(parent=self.sidebarFrame)
        self.navScrollArea.setStyleSheet("/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.navScrollArea.setWidgetResizable(True)
        self.navScrollArea.setObjectName("navScrollArea")
        self.navScrollContent = QtWidgets.QWidget()
        self.navScrollContent.setGeometry(QtCore.QRect(0, -220, 284, 719))
        self.navScrollContent.setStyleSheet("background-color: white;")
        self.navScrollContent.setObjectName("navScrollContent")
        self.navMainLayout = QtWidgets.QVBoxLayout(self.navScrollContent)
        self.navMainLayout.setContentsMargins(20, 28, 20, 28)
        self.navMainLayout.setSpacing(28)
        self.navMainLayout.setObjectName("navMainLayout")
        self.dashboardSectionLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.dashboardSectionLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.dashboardSectionLabel.setObjectName("dashboardSectionLabel")
        self.navMainLayout.addWidget(self.dashboardSectionLabel)
        self.buttonProfile = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonProfile.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonProfile.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonProfile.setCheckable(True)
        self.buttonProfile.setObjectName("buttonProfile")
        self.buttonGroupSubmenus = QtWidgets.QButtonGroup(StudentDashboard)
        self.buttonGroupSubmenus.setObjectName("buttonGroupSubmenus")
        self.buttonGroupSubmenus.addButton(self.buttonProfile)
        self.navMainLayout.addWidget(self.buttonProfile)
        self.userMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.userMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.userMgmtLabel.setObjectName("userMgmtLabel")
        self.navMainLayout.addWidget(self.userMgmtLabel)
        self.buttonCurrentSchedule = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonCurrentSchedule.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonCurrentSchedule.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCurrentSchedule.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonCurrentSchedule.setCheckable(True)
        self.buttonCurrentSchedule.setObjectName("buttonCurrentSchedule")
        self.buttonGroupSubmenus.addButton(self.buttonCurrentSchedule)
        self.navMainLayout.addWidget(self.buttonCurrentSchedule)
        self.courseMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.courseMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.courseMgmtLabel.setObjectName("courseMgmtLabel")
        self.navMainLayout.addWidget(self.courseMgmtLabel)
        self.buttonRegisterCourses = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonRegisterCourses.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonRegisterCourses.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRegisterCourses.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonRegisterCourses.setCheckable(True)
        self.buttonRegisterCourses.setObjectName("buttonRegisterCourses")
        self.buttonGroupSubmenus.addButton(self.buttonRegisterCourses)
        self.navMainLayout.addWidget(self.buttonRegisterCourses)
        self.buttonViewPrereqs = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonViewPrereqs.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonViewPrereqs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonViewPrereqs.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonViewPrereqs.setCheckable(True)
        self.buttonViewPrereqs.setObjectName("buttonViewPrereqs")
        self.buttonGroupSubmenus.addButton(self.buttonViewPrereqs)
        self.navMainLayout.addWidget(self.buttonViewPrereqs)
        self.buttonViewProgramPlans = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonViewProgramPlans.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonViewProgramPlans.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonViewProgramPlans.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonViewProgramPlans.setCheckable(True)
        self.buttonViewProgramPlans.setObjectName("buttonViewProgramPlans")
        self.buttonGroupSubmenus.addButton(self.buttonViewProgramPlans)
        self.navMainLayout.addWidget(self.buttonViewProgramPlans)
        self.buttonTranscript = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonTranscript.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonTranscript.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonTranscript.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #8c6fff;  /* slightly purple-ish on hover */\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(140, 111, 255, 0.10);  /* faint purple */\n"
"    color: #8c6fff; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #8c6fff;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(140, 111, 255, 0.18);  /* slightly darker purple on press */\n"
"}\n"
"")
        self.buttonTranscript.setCheckable(True)
        self.buttonTranscript.setObjectName("buttonTranscript")
        self.buttonGroupSubmenus.addButton(self.buttonTranscript)
        self.navMainLayout.addWidget(self.buttonTranscript)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.navMainLayout.addItem(spacerItem3)
        self.buttonLogout = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonLogout.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonLogout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonLogout.setStyleSheet("QPushButton {\n"
"    background-color: #fff5f5;\n"
"    border: 2px solid #fed7d7;\n"
"    border-radius: 12px;\n"
"    color: #e53e3e;\n"
"    font-weight: 700;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 18px;\n"
"    /* Add subtle shadow for depth */\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: #fed7d7;\n"
"}\n"
"\n"
"/* Pressed effect */\n"
"QPushButton:pressed {\n"
"    background-color: #fbb6b6; /* slightly darker */\n"
"    padding-left: 20px;        /* move text slightly right to simulate press */\n"
"    padding-top: 2px;          /* move text slightly down */\n"
"    border-color: #f56565;     /* darker border */\n"
"}\n"
"")
        self.buttonLogout.setObjectName("buttonLogout")
        self.navMainLayout.addWidget(self.buttonLogout)
        self.navScrollArea.setWidget(self.navScrollContent)
        self.sidebarLayout.addWidget(self.navScrollArea)
        self.mainHorizontalLayout.addWidget(self.sidebarFrame)
        self.mainContentWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainContentWidget.setStyleSheet("background-color: #f5f7fa;")
        self.mainContentWidget.setObjectName("mainContentWidget")
        self.mainContentLayout = QtWidgets.QVBoxLayout(self.mainContentWidget)
        self.mainContentLayout.setContentsMargins(0, 0, 0, 0)
        self.mainContentLayout.setSpacing(0)
        self.mainContentLayout.setObjectName("mainContentLayout")
        self.topBarFrame = QtWidgets.QFrame(parent=self.mainContentWidget)
        self.topBarFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.topBarFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.topBarFrame.setStyleSheet("background-color: white;")
        self.topBarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topBarFrame.setObjectName("topBarFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.topBarFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelPageTitle = QtWidgets.QLabel(parent=self.topBarFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPageTitle.sizePolicy().hasHeightForWidth())
        self.labelPageTitle.setSizePolicy(sizePolicy)
        self.labelPageTitle.setMinimumSize(QtCore.QSize(300, 30))
        self.labelPageTitle.setStyleSheet("font-size: 30px; font-weight: 900; color: #1a202c; background: transparent;")
        self.labelPageTitle.setObjectName("labelPageTitle")
        self.verticalLayout_2.addWidget(self.labelPageTitle)
        self.labelLastLogin = QtWidgets.QLabel(parent=self.topBarFrame)
        self.labelLastLogin.setStyleSheet("font-size: 14px; color: #718096; background: transparent;")
        self.labelLastLogin.setObjectName("labelLastLogin")
        self.verticalLayout_2.addWidget(self.labelLastLogin)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        self.mainContentLayout.addWidget(self.topBarFrame)
        self.frame = QtWidgets.QFrame(parent=self.mainContentWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setStyleSheet("\n"
"/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* ===== HORIZONTAL SCROLLBAR ===== */\n"
"QScrollBar:horizontal {\n"
"    height: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-width: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Left/Right buttons */\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.scrollAreaWidgetContents)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0Profile = QtWidgets.QWidget()
        self.page0Profile.setObjectName("page0Profile")
        self.stackedWidget.addWidget(self.page0Profile)
        self.page1AllStudents = QtWidgets.QWidget()
        self.page1AllStudents.setObjectName("page1AllStudents")
        self.stackedWidget.addWidget(self.page1AllStudents)
        self.page2PendingRequests = QtWidgets.QWidget()
        self.page2PendingRequests.setObjectName("page2PendingRequests")
        self.stackedWidget.addWidget(self.page2PendingRequests)
        self.page3ManageFaculty = QtWidgets.QWidget()
        self.page3ManageFaculty.setObjectName("page3ManageFaculty")
        self.stackedWidget.addWidget(self.page3ManageFaculty)
        self.page4ManageCourses = QtWidgets.QWidget()
        self.page4ManageCourses.setObjectName("page4ManageCourses")
        self.stackedWidget.addWidget(self.page4ManageCourses)
        self.page5ManageSections = QtWidgets.QWidget()
        self.page5ManageSections.setObjectName("page5ManageSections")
        self.stackedWidget.addWidget(self.page5ManageSections)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.mainContentLayout.addWidget(self.frame)
        self.mainHorizontalLayout.addWidget(self.mainContentWidget)
        StudentDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(StudentDashboard)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(StudentDashboard)

    def retranslateUi(self, StudentDashboard):
        _translate = QtCore.QCoreApplication.translate
        StudentDashboard.setWindowTitle(_translate("StudentDashboard", "Student Dashboard - ECE Registration System"))
        self.logoIconLabel.setText(_translate("StudentDashboard", "🎓"))
        self.labelLogoTitle.setText(_translate("StudentDashboard", "Student Panel"))
        self.labelLogoSubtitle.setText(_translate("StudentDashboard", "ECE Registration System"))
        self.labelStudentName.setText(_translate("StudentDashboard", "Student User"))
        self.labelStudentRole.setText(_translate("StudentDashboard", "Student"))
        self.labelStudentStatus.setText(_translate("StudentDashboard", "🟢 Online"))
        self.avatarLabel.setText(_translate("StudentDashboard", "ST"))
        self.dashboardSectionLabel.setText(_translate("StudentDashboard", "DASHBOARD"))
        self.buttonProfile.setText(_translate("StudentDashboard", "👤   Profile"))
        self.userMgmtLabel.setText(_translate("StudentDashboard", "USER MANAGEMENT"))
        self.buttonCurrentSchedule.setText(_translate("StudentDashboard", "📅 Current Schedule"))
        self.courseMgmtLabel.setText(_translate("StudentDashboard", "COURSE MANAGEMENT"))
        self.buttonRegisterCourses.setText(_translate("StudentDashboard", " 📝 Register Courses "))
        self.buttonViewPrereqs.setText(_translate("StudentDashboard", "🔗  View Prerequisetes"))
        self.buttonViewProgramPlans.setText(_translate("StudentDashboard", "📋  View Program Plans"))
        self.buttonTranscript.setText(_translate("StudentDashboard", " 📊 Transcript "))
        self.buttonLogout.setText(_translate("StudentDashboard", "🚪  Logout"))
        self.labelPageTitle.setText(_translate("StudentDashboard", "Dashboard Overview"))
        self.labelLastLogin.setText(_translate("StudentDashboard", "🏠 Last Login:"))
