# Form implementation generated from reading ui file 'edit_name.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditNameDialog(object):
    def setupUi(self, EditNameDialog):
        EditNameDialog.setObjectName("EditNameDialog")
        EditNameDialog.resize(505, 444)
        EditNameDialog.setMinimumSize(QtCore.QSize(0, 0))
        EditNameDialog.setMaximumSize(QtCore.QSize(780, 580))
        EditNameDialog.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(EditNameDialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.headerFrame = QtWidgets.QFrame(parent=EditNameDialog)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.headerFrame.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f093fb, stop:1 #f5576c); border-radius: 0px;")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(30, 20, 30, 20)
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.labelTitle.setStyleSheet("font-size: 24px; font-weight: bold; color: white; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addWidget(self.headerFrame)
        self.scrollArea = QtWidgets.QScrollArea(parent=EditNameDialog)
        self.scrollArea.setStyleSheet("border: none; background-color: #f5f7fa;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 505, 284))
        self.scrollContent.setStyleSheet("background-color: #f5f7fa;")
        self.scrollContent.setObjectName("scrollContent")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollContent)
        self.gridLayout_3.setContentsMargins(15, 10, 15, 0)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelName = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelName.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.scrollContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFullName.sizePolicy().hasHeightForWidth())
        self.lineEditFullName.setSizePolicy(sizePolicy)
        self.lineEditFullName.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditFullName.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditFullName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditFullName.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.verticalLayout.addWidget(self.lineEditFullName)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollContent)
        self.pushButton.setGeometry(QtCore.QRect(198, 169, 62, 16))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea.setWidget(self.scrollContent)
        self.mainLayout.addWidget(self.scrollArea)
        self.footerFrame = QtWidgets.QFrame(parent=EditNameDialog)
        self.footerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.footerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.footerFrame.setStyleSheet("background-color: white; border-top: 2px solid #e0e0e0;")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setObjectName("footerFrame")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerFrame)
        self.footerLayout.setContentsMargins(30, 20, 30, 20)
        self.footerLayout.setObjectName("footerLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem2)
        self.buttonCancel = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    color: #5a6c7d;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* darker grey for pressed feedback */\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.footerLayout.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonSave.setEnabled(True)
        self.buttonSave.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonSave.setStyleSheet("QPushButton {\n"
"    background-color: #f5576c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background-color 150ms;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e5475c;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d43f52;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;  /* gray background for disabled */\n"
"    color: #666666;             /* darker gray text */\n"
"}")
        self.buttonSave.setObjectName("buttonSave")
        self.footerLayout.addWidget(self.buttonSave)
        self.mainLayout.addWidget(self.footerFrame)

        self.retranslateUi(EditNameDialog)
        QtCore.QMetaObject.connectSlotsByName(EditNameDialog)

    def retranslateUi(self, EditNameDialog):
        _translate = QtCore.QCoreApplication.translate
        EditNameDialog.setWindowTitle(_translate("EditNameDialog", "Edit Name"))
        self.labelTitle.setText(_translate("EditNameDialog", "🗣️  Edit Name"))
        self.labelName.setText(_translate("EditNameDialog", "Full Name *"))
        self.lineEditFullName.setPlaceholderText(_translate("EditNameDialog", "Salem Ahmad Saleh"))
        self.pushButton.setText(_translate("EditNameDialog", "PushButton"))
        self.buttonCancel.setText(_translate("EditNameDialog", "Cancel"))
        self.buttonSave.setText(_translate("EditNameDialog", "💾  Save"))
