# Form implementation generated from reading ui file 'admin_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AdminDashboard(object):
    def setupUi(self, AdminDashboard):
        AdminDashboard.setObjectName("AdminDashboard")
        AdminDashboard.resize(1100, 650)
        AdminDashboard.setMinimumSize(QtCore.QSize(1000, 600))
        AdminDashboard.setStyleSheet("QMainWindow { background-color: #f5f7fa; }")
        self.centralwidget = QtWidgets.QWidget(parent=AdminDashboard)
        self.centralwidget.setStyleSheet("background-color: #f5f7fa;")
        self.centralwidget.setObjectName("centralwidget")
        self.mainHorizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.mainHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.mainHorizontalLayout.setSpacing(0)
        self.mainHorizontalLayout.setObjectName("mainHorizontalLayout")
        self.sidebarFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebarFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.sidebarFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.sidebarFrame.setStyleSheet("QFrame { background-color: white; }")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.sidebarFrame)
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarLayout.setSpacing(0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.headerWidget = QtWidgets.QWidget(parent=self.sidebarFrame)
        self.headerWidget.setMinimumSize(QtCore.QSize(0, 210))
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 210))
        self.headerWidget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f093fb, stop:1 #f5576c);")
        self.headerWidget.setObjectName("headerWidget")
        self.headerLayout = QtWidgets.QVBoxLayout(self.headerWidget)
        self.headerLayout.setContentsMargins(25, 32, 25, 28)
        self.headerLayout.setSpacing(20)
        self.headerLayout.setObjectName("headerLayout")
        self.logoHLayout = QtWidgets.QHBoxLayout()
        self.logoHLayout.setObjectName("logoHLayout")
        self.logoIconLabel = QtWidgets.QLabel(parent=self.headerWidget)
        self.logoIconLabel.setMinimumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setMaximumSize(QtCore.QSize(64, 64))
        self.logoIconLabel.setStyleSheet("background-color: white; border-radius: 15px; font-size: 34px;")
        self.logoIconLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logoIconLabel.setObjectName("logoIconLabel")
        self.logoHLayout.addWidget(self.logoIconLabel)
        self.logoTextLayout = QtWidgets.QVBoxLayout()
        self.logoTextLayout.setSpacing(4)
        self.logoTextLayout.setObjectName("logoTextLayout")
        self.labelLogoTitle = QtWidgets.QLabel(parent=self.headerWidget)
        self.labelLogoTitle.setStyleSheet("color: white; font-size: 23px; font-weight: 800; background: transparent;")
        self.labelLogoTitle.setObjectName("labelLogoTitle")
        self.logoTextLayout.addWidget(self.labelLogoTitle)
        self.labelLogoSubtitle = QtWidgets.QLabel(parent=self.headerWidget)
        self.labelLogoSubtitle.setStyleSheet("color: rgba(255,255,255,0.95); font-size: 13px; background: transparent;")
        self.labelLogoSubtitle.setObjectName("labelLogoSubtitle")
        self.logoTextLayout.addWidget(self.labelLogoSubtitle)
        self.logoHLayout.addLayout(self.logoTextLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.logoHLayout.addItem(spacerItem)
        self.headerLayout.addLayout(self.logoHLayout)
        self.profileFrame = QtWidgets.QFrame(parent=self.headerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profileFrame.sizePolicy().hasHeightForWidth())
        self.profileFrame.setSizePolicy(sizePolicy)
        self.profileFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.profileFrame.setStyleSheet("QFrame {\n"
"    background-color: rgba(255,255,255,0.22);\n"
"    border-radius: 15px;\n"
"    border: 1px solid rgba(255,255,255,0.35);\n"
"}")
        self.profileFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.profileFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.profileFrame.setObjectName("profileFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.profileFrame)
        self.gridLayout.setContentsMargins(-1, 5, 5, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelAdminName = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelAdminName.setMinimumSize(QtCore.QSize(20, 20))
        self.labelAdminName.setStyleSheet("color: white; \n"
"font-size: 17px; \n"
"font-weight: 800;\n"
"background: transparent;\n"
"border: transparent")
        self.labelAdminName.setObjectName("labelAdminName")
        self.verticalLayout.addWidget(self.labelAdminName)
        self.labelAdminRole = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelAdminRole.setMinimumSize(QtCore.QSize(0, 20))
        self.labelAdminRole.setStyleSheet("color: rgba(255,255,255,0.88); \n"
"font-size: 13px; \n"
"font-weight: 500;\n"
"background: transparent;\n"
"border: transparent")
        self.labelAdminRole.setObjectName("labelAdminRole")
        self.verticalLayout.addWidget(self.labelAdminRole)
        self.adminStatus = QtWidgets.QLabel(parent=self.profileFrame)
        self.adminStatus.setMinimumSize(QtCore.QSize(0, 20))
        self.adminStatus.setStyleSheet("color: rgba(255,255,255,0.95); \n"
"font-size: 11px; \n"
"font-weight: 600;\n"
"border: transparent;\n"
"background-color: transparent")
        self.adminStatus.setObjectName("adminStatus")
        self.verticalLayout.addWidget(self.adminStatus)
        self.gridLayout.addLayout(self.verticalLayout, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 3, 1, 1)
        self.labelAvatar = QtWidgets.QLabel(parent=self.profileFrame)
        self.labelAvatar.setMinimumSize(QtCore.QSize(60, 60))
        self.labelAvatar.setMaximumSize(QtCore.QSize(60, 60))
        self.labelAvatar.setStyleSheet("background-color: white;\n"
"color: #f5576c;\n"
"border-radius: 30px;\n"
"font-size: 26px;\n"
"font-weight: 900;")
        self.labelAvatar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelAvatar.setObjectName("labelAvatar")
        self.gridLayout.addWidget(self.labelAvatar, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.headerLayout.addWidget(self.profileFrame)
        self.sidebarLayout.addWidget(self.headerWidget)
        self.navScrollArea = QtWidgets.QScrollArea(parent=self.sidebarFrame)
        self.navScrollArea.setStyleSheet("/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.navScrollArea.setWidgetResizable(True)
        self.navScrollArea.setObjectName("navScrollArea")
        self.navScrollContent = QtWidgets.QWidget()
        self.navScrollContent.setGeometry(QtCore.QRect(0, -101, 284, 1023))
        self.navScrollContent.setStyleSheet("background-color: white;")
        self.navScrollContent.setObjectName("navScrollContent")
        self.navMainLayout = QtWidgets.QVBoxLayout(self.navScrollContent)
        self.navMainLayout.setContentsMargins(20, 28, 20, 28)
        self.navMainLayout.setSpacing(28)
        self.navMainLayout.setObjectName("navMainLayout")
        self.dashboardSectionLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.dashboardSectionLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.dashboardSectionLabel.setObjectName("dashboardSectionLabel")
        self.navMainLayout.addWidget(self.dashboardSectionLabel)
        self.buttonProfile = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonProfile.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonProfile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonProfile.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonProfile.setCheckable(True)
        self.buttonProfile.setObjectName("buttonProfile")
        self.buttonGroupSubmenus = QtWidgets.QButtonGroup(AdminDashboard)
        self.buttonGroupSubmenus.setObjectName("buttonGroupSubmenus")
        self.buttonGroupSubmenus.addButton(self.buttonProfile)
        self.navMainLayout.addWidget(self.buttonProfile)
        self.userMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.userMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.userMgmtLabel.setObjectName("userMgmtLabel")
        self.navMainLayout.addWidget(self.userMgmtLabel)
        self.buttonAllStudents = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonAllStudents.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonAllStudents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonAllStudents.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonAllStudents.setCheckable(True)
        self.buttonAllStudents.setObjectName("buttonAllStudents")
        self.buttonGroupSubmenus.addButton(self.buttonAllStudents)
        self.navMainLayout.addWidget(self.buttonAllStudents)
        self.buttonPendingRequests = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonPendingRequests.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonPendingRequests.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonPendingRequests.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonPendingRequests.setCheckable(True)
        self.buttonPendingRequests.setObjectName("buttonPendingRequests")
        self.buttonGroupSubmenus.addButton(self.buttonPendingRequests)
        self.navMainLayout.addWidget(self.buttonPendingRequests)
        self.buttonManageStudents = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageStudents.setEnabled(True)
        self.buttonManageStudents.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageStudents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageStudents.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"\n"
"/* DISABLED STATE */\n"
"QPushButton:disabled {\n"
"    background-color: transparent;\n"
"    color: #a0a0a0;        /* muted grey for disabled */\n"
"    border-left: none;      /* remove left bar if present */\n"
"    font-weight: normal;    /* remove bold */\n"
"}\n"
"")
        self.buttonManageStudents.setCheckable(True)
        self.buttonManageStudents.setObjectName("buttonManageStudents")
        self.buttonGroupSubmenus.addButton(self.buttonManageStudents)
        self.navMainLayout.addWidget(self.buttonManageStudents)
        self.buttonManageFaculty = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageFaculty.setEnabled(True)
        self.buttonManageFaculty.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageFaculty.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageFaculty.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"\n"
"/* DISABLED STATE */\n"
"QPushButton:disabled {\n"
"    background-color: transparent;\n"
"    color: #a0a0a0;        /* muted grey for disabled */\n"
"    border-left: none;      /* remove left bar if present */\n"
"    font-weight: normal;    /* remove bold */\n"
"}\n"
"")
        self.buttonManageFaculty.setCheckable(True)
        self.buttonManageFaculty.setObjectName("buttonManageFaculty")
        self.buttonGroupSubmenus.addButton(self.buttonManageFaculty)
        self.navMainLayout.addWidget(self.buttonManageFaculty)
        self.courseMgmtLabel = QtWidgets.QLabel(parent=self.navScrollContent)
        self.courseMgmtLabel.setStyleSheet("color: #a0aec0; font-size: 11px; font-weight: 800; background: transparent;")
        self.courseMgmtLabel.setObjectName("courseMgmtLabel")
        self.navMainLayout.addWidget(self.courseMgmtLabel)
        self.buttonManageCourses = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageCourses.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageCourses.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageCourses.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManageCourses.setCheckable(True)
        self.buttonManageCourses.setObjectName("buttonManageCourses")
        self.buttonGroupSubmenus.addButton(self.buttonManageCourses)
        self.navMainLayout.addWidget(self.buttonManageCourses)
        self.buttonManagePrereqs = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManagePrereqs.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManagePrereqs.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManagePrereqs.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManagePrereqs.setCheckable(True)
        self.buttonManagePrereqs.setObjectName("buttonManagePrereqs")
        self.buttonGroupSubmenus.addButton(self.buttonManagePrereqs)
        self.navMainLayout.addWidget(self.buttonManagePrereqs)
        self.buttonManageSections = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonManageSections.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonManageSections.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonManageSections.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonManageSections.setCheckable(True)
        self.buttonManageSections.setObjectName("buttonManageSections")
        self.buttonGroupSubmenus.addButton(self.buttonManageSections)
        self.navMainLayout.addWidget(self.buttonManageSections)
        self.buttonProgramPlans = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonProgramPlans.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonProgramPlans.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonProgramPlans.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE (optional but clean) */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"")
        self.buttonProgramPlans.setCheckable(True)
        self.buttonProgramPlans.setObjectName("buttonProgramPlans")
        self.buttonGroupSubmenus.addButton(self.buttonProgramPlans)
        self.navMainLayout.addWidget(self.buttonProgramPlans)
        self.buttonRegisterForStudents = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonRegisterForStudents.setEnabled(False)
        self.buttonRegisterForStudents.setMinimumSize(QtCore.QSize(0, 48))
        self.buttonRegisterForStudents.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRegisterForStudents.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    color: #5a6c7d;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"/* CHECKED / TOGGLED STATE */\n"
"QPushButton:checked {\n"
"    background-color: rgba(245, 87, 108, 0.10);  /* faint pink */\n"
"    color: #f5576c; \n"
"    font-weight: bold;\n"
"    border-left: 4px solid #f5576c;\n"
"    padding-left: 11px; /* adjust so bar doesn’t push content too far */\n"
"}\n"
"\n"
"/* PRESSED STATE */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(245, 87, 108, 0.18);\n"
"}\n"
"\n"
"/* DISABLED STATE */\n"
"QPushButton:disabled {\n"
"    background-color: transparent;\n"
"    color: #a0a0a0;        /* muted grey for disabled */\n"
"    border-left: none;      /* remove left bar if present */\n"
"    font-weight: normal;    /* remove bold */\n"
"}\n"
"")
        self.buttonRegisterForStudents.setCheckable(True)
        self.buttonRegisterForStudents.setObjectName("buttonRegisterForStudents")
        self.navMainLayout.addWidget(self.buttonRegisterForStudents)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.navMainLayout.addItem(spacerItem3)
        self.buttonLogout = QtWidgets.QPushButton(parent=self.navScrollContent)
        self.buttonLogout.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonLogout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonLogout.setStyleSheet("QPushButton {\n"
"    background-color: #fff5f5;\n"
"    border: 2px solid #fed7d7;\n"
"    border-radius: 12px;\n"
"    color: #e53e3e;\n"
"    font-weight: 700;\n"
"    font-size: 14px;\n"
"    text-align: left;\n"
"    padding-left: 18px;\n"
"    /* Add subtle shadow for depth */\n"
"    box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QPushButton:hover {\n"
"    background-color: #fed7d7;\n"
"}\n"
"\n"
"/* Pressed effect */\n"
"QPushButton:pressed {\n"
"    background-color: #fbb6b6; /* slightly darker */\n"
"    padding-left: 20px;        /* move text slightly right to simulate press */\n"
"    padding-top: 2px;          /* move text slightly down */\n"
"    border-color: #f56565;     /* darker border */\n"
"}\n"
"")
        self.buttonLogout.setObjectName("buttonLogout")
        self.navMainLayout.addWidget(self.buttonLogout)
        self.navScrollArea.setWidget(self.navScrollContent)
        self.sidebarLayout.addWidget(self.navScrollArea)
        self.mainHorizontalLayout.addWidget(self.sidebarFrame)
        self.mainContentWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.mainContentWidget.setStyleSheet("background-color: #f5f7fa;")
        self.mainContentWidget.setObjectName("mainContentWidget")
        self.mainContentLayout = QtWidgets.QVBoxLayout(self.mainContentWidget)
        self.mainContentLayout.setContentsMargins(0, 0, 0, 0)
        self.mainContentLayout.setSpacing(0)
        self.mainContentLayout.setObjectName("mainContentLayout")
        self.topBarFrame = QtWidgets.QFrame(parent=self.mainContentWidget)
        self.topBarFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.topBarFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.topBarFrame.setStyleSheet("background-color: white;")
        self.topBarFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.topBarFrame.setObjectName("topBarFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.topBarFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelPageTitle = QtWidgets.QLabel(parent=self.topBarFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPageTitle.sizePolicy().hasHeightForWidth())
        self.labelPageTitle.setSizePolicy(sizePolicy)
        self.labelPageTitle.setMinimumSize(QtCore.QSize(300, 30))
        self.labelPageTitle.setStyleSheet("font-size: 30px; font-weight: 900; color: #1a202c; background: transparent;")
        self.labelPageTitle.setObjectName("labelPageTitle")
        self.verticalLayout_2.addWidget(self.labelPageTitle)
        self.labelLastLogin = QtWidgets.QLabel(parent=self.topBarFrame)
        self.labelLastLogin.setStyleSheet("font-size: 14px; color: #718096; background: transparent;")
        self.labelLastLogin.setObjectName("labelLastLogin")
        self.verticalLayout_2.addWidget(self.labelLastLogin)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        self.mainContentLayout.addWidget(self.topBarFrame)
        self.frame = QtWidgets.QFrame(parent=self.mainContentWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.frame)
        self.scrollArea.setStyleSheet("\n"
"/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* ===== HORIZONTAL SCROLLBAR ===== */\n"
"QScrollBar:horizontal {\n"
"    height: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-width: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Left/Right buttons */\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 778, 538))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.scrollAreaWidgetContents)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page0Profile = QtWidgets.QWidget()
        self.page0Profile.setObjectName("page0Profile")
        self.stackedWidget.addWidget(self.page0Profile)
        self.page1AllStudents = QtWidgets.QWidget()
        self.page1AllStudents.setObjectName("page1AllStudents")
        self.stackedWidget.addWidget(self.page1AllStudents)
        self.page2PendingRequests = QtWidgets.QWidget()
        self.page2PendingRequests.setObjectName("page2PendingRequests")
        self.stackedWidget.addWidget(self.page2PendingRequests)
        self.page3ManageFaculty = QtWidgets.QWidget()
        self.page3ManageFaculty.setObjectName("page3ManageFaculty")
        self.stackedWidget.addWidget(self.page3ManageFaculty)
        self.page4ManageCourses = QtWidgets.QWidget()
        self.page4ManageCourses.setObjectName("page4ManageCourses")
        self.stackedWidget.addWidget(self.page4ManageCourses)
        self.page5ManageSections = QtWidgets.QWidget()
        self.page5ManageSections.setObjectName("page5ManageSections")
        self.stackedWidget.addWidget(self.page5ManageSections)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.mainContentLayout.addWidget(self.frame)
        self.mainHorizontalLayout.addWidget(self.mainContentWidget)
        AdminDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdminDashboard)
        self.stackedWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(AdminDashboard)

    def retranslateUi(self, AdminDashboard):
        _translate = QtCore.QCoreApplication.translate
        AdminDashboard.setWindowTitle(_translate("AdminDashboard", "Admin Dashboard - ECE Registration System"))
        self.logoIconLabel.setText(_translate("AdminDashboard", "🛠️"))
        self.labelLogoTitle.setText(_translate("AdminDashboard", "Admin Panel"))
        self.labelLogoSubtitle.setText(_translate("AdminDashboard", "ECE Registration System"))
        self.labelAdminName.setText(_translate("AdminDashboard", "Admin User"))
        self.labelAdminRole.setText(_translate("AdminDashboard", "Administrator"))
        self.adminStatus.setText(_translate("AdminDashboard", "🟢 Online"))
        self.labelAvatar.setText(_translate("AdminDashboard", "AD"))
        self.dashboardSectionLabel.setText(_translate("AdminDashboard", "DASHBOARD"))
        self.buttonProfile.setText(_translate("AdminDashboard", "📊  Profile"))
        self.userMgmtLabel.setText(_translate("AdminDashboard", "USER MANAGEMENT"))
        self.buttonAllStudents.setText(_translate("AdminDashboard", "👥  All Students (205)"))
        self.buttonPendingRequests.setText(_translate("AdminDashboard", "⏳  Pending Requests (12)"))
        self.buttonManageStudents.setText(_translate("AdminDashboard", "👨🏼‍🎓  Manage Students"))
        self.buttonManageFaculty.setText(_translate("AdminDashboard", "👨‍🏫  Manage Faculty"))
        self.courseMgmtLabel.setText(_translate("AdminDashboard", "COURSE MANAGEMENT"))
        self.buttonManageCourses.setText(_translate("AdminDashboard", "📚  Manage Courses (32)"))
        self.buttonManagePrereqs.setText(_translate("AdminDashboard", "🔗  Manage Prerequisetes"))
        self.buttonManageSections.setText(_translate("AdminDashboard", "✏️  Manage Sections"))
        self.buttonProgramPlans.setText(_translate("AdminDashboard", "📋  Program Plans"))
        self.buttonRegisterForStudents.setText(_translate("AdminDashboard", "🙋🏻‍♂️ Register for Students -WIP-"))
        self.buttonLogout.setText(_translate("AdminDashboard", "🚪  Logout"))
        self.labelPageTitle.setText(_translate("AdminDashboard", "Dashboard Overview"))
        self.labelLastLogin.setText(_translate("AdminDashboard", "🏠 Last Login {lastLogin}"))
