# Form implementation generated from reading ui file 'edit_course_to_plan_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddCourseDialog(object):
    def setupUi(self, AddCourseDialog):
        AddCourseDialog.setObjectName("AddCourseDialog")
        AddCourseDialog.resize(505, 444)
        AddCourseDialog.setMinimumSize(QtCore.QSize(0, 0))
        AddCourseDialog.setMaximumSize(QtCore.QSize(780, 580))
        AddCourseDialog.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(AddCourseDialog)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.headerFrame = QtWidgets.QFrame(parent=AddCourseDialog)
        self.headerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.headerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.headerFrame.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #f093fb, stop:1 #f5576c); border-radius: 0px;")
        self.headerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.headerFrame.setObjectName("headerFrame")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerFrame)
        self.headerLayout.setContentsMargins(30, 20, 30, 20)
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.headerFrame)
        self.labelTitle.setStyleSheet("font-size: 24px; font-weight: bold; color: white; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addWidget(self.headerFrame)
        self.scrollArea = QtWidgets.QScrollArea(parent=AddCourseDialog)
        self.scrollArea.setStyleSheet("border: none; background-color: #f5f7fa;")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollContent = QtWidgets.QWidget()
        self.scrollContent.setGeometry(QtCore.QRect(0, 0, 505, 284))
        self.scrollContent.setStyleSheet("background-color: #f5f7fa;")
        self.scrollContent.setObjectName("scrollContent")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollContent)
        self.gridLayout_3.setContentsMargins(15, 10, 15, 0)
        self.gridLayout_3.setHorizontalSpacing(15)
        self.gridLayout_3.setVerticalSpacing(30)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelCourseName = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCourseName.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCourseName.setObjectName("labelCourseName")
        self.verticalLayout.addWidget(self.labelCourseName)
        self.comboBoxSelectCourse = QtWidgets.QComboBox(parent=self.scrollContent)
        self.comboBoxSelectCourse.setMinimumSize(QtCore.QSize(200, 45))
        self.comboBoxSelectCourse.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBoxSelectCourse.setStyleSheet("/* ----------------- QComboBox Base ----------------- */\n"
"QComboBox {\n"
"    border: 2px solid #E0E0E0;          /* main border */\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                   /* Matches QLineEdit padding */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"}\n"
"\n"
"/* Focused state */\n"
"QComboBox:focus {\n"
"    border: 2px solid #667EEA; \n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* ----------------- Drop-down Arrow ----------------- */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-width: 1px;\n"
"    border-left-color: #E0E0E0;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 12px;       /* rounder corners */\n"
"    border-bottom-right-radius: 12px;    /* rounder corners */\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove ugly black border on hover/focus */\n"
"QComboBox::drop-down:hover,\n"
"QComboBox::drop-down:focus {\n"
"    border-left-color: #667EEA;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Modern, visible arrow using simple chevron */\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: solid #667EEA;\n"
"    border-width: 0 2px 2px 0;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"/* ----------------- Dropdown Popup ----------------- */\n"
"/* Dropdown Popup */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fdfdfd;          /* slightly off-white */\n"
"    border: 2px solid #E0E0E0;          /* subtle grey border */\n"
"    border-radius: 8px;                  /* may not be perfect on Windows */\n"
"    color: #111111;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"    selection-background-color: #667EEA;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items hover/selection */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(102, 126, 234, 0.1);\n"
"    color: #111111;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #667EEA;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Error highlight for combo box */\n"
"QComboBox[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}")
        self.comboBoxSelectCourse.setEditable(True)
        self.comboBoxSelectCourse.setObjectName("comboBoxSelectCourse")
        self.comboBoxSelectCourse.addItem("")
        self.verticalLayout.addWidget(self.comboBoxSelectCourse)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelCourseCode = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCourseCode.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCourseCode.setObjectName("labelCourseCode")
        self.verticalLayout_2.addWidget(self.labelCourseCode)
        self.comboBoxSelectProgram = QtWidgets.QComboBox(parent=self.scrollContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSelectProgram.sizePolicy().hasHeightForWidth())
        self.comboBoxSelectProgram.setSizePolicy(sizePolicy)
        self.comboBoxSelectProgram.setMinimumSize(QtCore.QSize(150, 40))
        self.comboBoxSelectProgram.setMaximumSize(QtCore.QSize(16777215, 65))
        self.comboBoxSelectProgram.setStyleSheet("/* ----------------- QComboBox Base ----------------- */\n"
"QComboBox {\n"
"    border: 2px solid #E0E0E0;          /* main border */\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                   /* Matches QLineEdit padding */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"}\n"
"\n"
"/* Focused state */\n"
"QComboBox:focus {\n"
"    border: 2px solid #667EEA; \n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* ----------------- Drop-down Arrow ----------------- */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-width: 1px;\n"
"    border-left-color: #E0E0E0;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 12px;       /* rounder corners */\n"
"    border-bottom-right-radius: 12px;    /* rounder corners */\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove ugly black border on hover/focus */\n"
"QComboBox::drop-down:hover,\n"
"QComboBox::drop-down:focus {\n"
"    border-left-color: #667EEA;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Modern, visible arrow using simple chevron */\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: solid #667EEA;\n"
"    border-width: 0 2px 2px 0;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"/* ----------------- Dropdown Popup ----------------- */\n"
"/* Dropdown Popup */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fdfdfd;          /* slightly off-white */\n"
"    border: 2px solid #E0E0E0;          /* subtle grey border */\n"
"    border-radius: 8px;                  /* may not be perfect on Windows */\n"
"    color: #111111;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"    selection-background-color: #667EEA;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items hover/selection */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(102, 126, 234, 0.1);\n"
"    color: #111111;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #667EEA;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Error highlight for combo box */\n"
"QComboBox[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}")
        self.comboBoxSelectProgram.setObjectName("comboBoxSelectProgram")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.verticalLayout_2.addWidget(self.comboBoxSelectProgram)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelCreditHours = QtWidgets.QLabel(parent=self.scrollContent)
        self.labelCreditHours.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelCreditHours.setObjectName("labelCreditHours")
        self.verticalLayout_3.addWidget(self.labelCreditHours)
        self.spinBoxLevel = QtWidgets.QSpinBox(parent=self.scrollContent)
        self.spinBoxLevel.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                        /* same padding as your QLineEdit */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* The text area inside the spinbox */\n"
"QSpinBox QLineEdit {\n"
"    color: #111111;\n"
"    font-style: normal;\n"
"}\n"
"\n"
"/* Placeholder text styling (requires setting placeholder via spinbox.lineEdit().setPlaceholderText()) */\n"
"QSpinBox QLineEdit:disabled {\n"
"    color: #888888;\n"
"}\n"
"\n"
"/* Hide the up/down arrows completely */\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    width: 0;\n"
"    height: 0;\n"
"    border: none;\n"
"}\n"
"")
        self.spinBoxLevel.setMinimum(1)
        self.spinBoxLevel.setMaximum(10)
        self.spinBoxLevel.setObjectName("spinBoxLevel")
        self.verticalLayout_3.addWidget(self.spinBoxLevel)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3.addLayout(self.gridLayout, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(17, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.scrollContent)
        self.pushButton.setGeometry(QtCore.QRect(198, 169, 62, 16))
        self.pushButton.setObjectName("pushButton")
        self.scrollArea.setWidget(self.scrollContent)
        self.mainLayout.addWidget(self.scrollArea)
        self.footerFrame = QtWidgets.QFrame(parent=AddCourseDialog)
        self.footerFrame.setMinimumSize(QtCore.QSize(0, 80))
        self.footerFrame.setMaximumSize(QtCore.QSize(16777215, 80))
        self.footerFrame.setStyleSheet("background-color: white; border-top: 2px solid #e0e0e0;")
        self.footerFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.footerFrame.setObjectName("footerFrame")
        self.footerLayout = QtWidgets.QHBoxLayout(self.footerFrame)
        self.footerLayout.setContentsMargins(30, 20, 30, 20)
        self.footerLayout.setObjectName("footerLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem2)
        self.buttonCancel = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonCancel.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonCancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCancel.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;\n"
"    color: #5a6c7d;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0; /* darker grey for pressed feedback */\n"
"    border-color: #f5576c;\n"
"    color: #f5576c;\n"
"}")
        self.buttonCancel.setObjectName("buttonCancel")
        self.footerLayout.addWidget(self.buttonCancel)
        self.buttonSave = QtWidgets.QPushButton(parent=self.footerFrame)
        self.buttonSave.setEnabled(True)
        self.buttonSave.setMinimumSize(QtCore.QSize(120, 45))
        self.buttonSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonSave.setStyleSheet("QPushButton {\n"
"    background-color: #f5576c;\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background-color 150ms;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #e5475c;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #d43f52;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #cccccc;  /* gray background for disabled */\n"
"    color: #666666;             /* darker gray text */\n"
"}")
        self.buttonSave.setObjectName("buttonSave")
        self.footerLayout.addWidget(self.buttonSave)
        self.mainLayout.addWidget(self.footerFrame)

        self.retranslateUi(AddCourseDialog)
        QtCore.QMetaObject.connectSlotsByName(AddCourseDialog)

    def retranslateUi(self, AddCourseDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCourseDialog.setWindowTitle(_translate("AddCourseDialog", "Add New Course"))
        self.labelTitle.setText(_translate("AddCourseDialog", "✍🏻  Edit Course Plan"))
        self.labelCourseName.setText(_translate("AddCourseDialog", "Course Name *"))
        self.comboBoxSelectCourse.setItemText(0, _translate("AddCourseDialog", "Select a course..."))
        self.labelCourseCode.setText(_translate("AddCourseDialog", "Program *"))
        self.comboBoxSelectProgram.setPlaceholderText(_translate("AddCourseDialog", "Select Program..."))
        self.comboBoxSelectProgram.setItemText(0, _translate("AddCourseDialog", "Computer"))
        self.comboBoxSelectProgram.setItemText(1, _translate("AddCourseDialog", "Communication"))
        self.comboBoxSelectProgram.setItemText(2, _translate("AddCourseDialog", "Power"))
        self.comboBoxSelectProgram.setItemText(3, _translate("AddCourseDialog", "Biomedical"))
        self.labelCreditHours.setText(_translate("AddCourseDialog", "Level *"))
        self.pushButton.setText(_translate("AddCourseDialog", "PushButton"))
        self.buttonCancel.setText(_translate("AddCourseDialog", "Cancel"))
        self.buttonSave.setText(_translate("AddCourseDialog", "💾  Save Course"))
