# Form implementation generated from reading ui file 'auth_stackedwidget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthStackedWidget(object):
    def setupUi(self, AuthStackedWidget):
        AuthStackedWidget.setObjectName("AuthStackedWidget")
        AuthStackedWidget.resize(600, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qrc_images/assets/images/login_bg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AuthStackedWidget.setWindowIcon(icon)
        AuthStackedWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(AuthStackedWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidgetAuth = QtWidgets.QStackedWidget(parent=AuthStackedWidget)
        self.stackedWidgetAuth.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.stackedWidgetAuth.setObjectName("stackedWidgetAuth")
        self.horizontalLayout.addWidget(self.stackedWidgetAuth)

        self.retranslateUi(AuthStackedWidget)
        self.stackedWidgetAuth.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AuthStackedWidget)

    def retranslateUi(self, AuthStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        AuthStackedWidget.setWindowTitle(_translate("AuthStackedWidget", "User Authentication - ECE-Registration System"))
