# Form implementation generated from reading ui file 'auth_stackedwidget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AuthStackedWidget(object):
    def setupUi(self, AuthStackedWidget):
        AuthStackedWidget.setObjectName("AuthStackedWidget")
        AuthStackedWidget.resize(600, 700)
        AuthStackedWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(AuthStackedWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidgetAuth = QtWidgets.QStackedWidget(parent=AuthStackedWidget)
        self.stackedWidgetAuth.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.stackedWidgetAuth.setObjectName("stackedWidgetAuth")
        self.page0Login = LoginWidget()
        self.page0Login.setObjectName("page0Login")
        self.stackedWidgetAuth.addWidget(self.page0Login)
        self.page1Register = CreateAccountWidget()
        self.page1Register.setObjectName("page1Register")
        self.stackedWidgetAuth.addWidget(self.page1Register)
        self.page2Reset = ResetPasswordWidget()
        self.page2Reset.setObjectName("page2Reset")
        self.stackedWidgetAuth.addWidget(self.page2Reset)
        self.page3ConfirmEmail = ConfirmEmailWidget()
        self.page3ConfirmEmail.setObjectName("page3ConfirmEmail")
        self.stackedWidgetAuth.addWidget(self.page3ConfirmEmail)
        self.horizontalLayout.addWidget(self.stackedWidgetAuth)

        self.retranslateUi(AuthStackedWidget)
        self.stackedWidgetAuth.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(AuthStackedWidget)

    def retranslateUi(self, AuthStackedWidget):
        _translate = QtCore.QCoreApplication.translate
        AuthStackedWidget.setWindowTitle(_translate("AuthStackedWidget", "Form"))
from class_confirm_email_widget import ConfirmEmailWidget
from class_create_account_widget import CreateAccountWidget
from class_login_widget import LoginWidget
from class_reset_password_widget import ResetPasswordWidget
