# Form implementation generated from reading ui file 'confirm_email_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConfirmEmailWidget(object):
    def setupUi(self, ConfirmEmailWidget):
        ConfirmEmailWidget.setObjectName("ConfirmEmailWidget")
        ConfirmEmailWidget.resize(600, 705)
        icon = QtGui.QIcon.fromTheme(QtGui.QIcon.ThemeIcon.MailForward)
        ConfirmEmailWidget.setWindowIcon(icon)
        ConfirmEmailWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget#ConfirmEmailWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ConfirmEmailWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.confirmEmailPanel = QtWidgets.QFrame(parent=ConfirmEmailWidget)
        self.confirmEmailPanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirmEmailPanel.sizePolicy().hasHeightForWidth())
        self.confirmEmailPanel.setSizePolicy(sizePolicy)
        self.confirmEmailPanel.setMinimumSize(QtCore.QSize(385, 0))
        self.confirmEmailPanel.setMaximumSize(QtCore.QSize(650, 700))
        self.confirmEmailPanel.setStyleSheet("QFrame#confirmEmailPanel {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"    padding: 30px;\n"
"}\n"
"")
        self.confirmEmailPanel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.confirmEmailPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.confirmEmailPanel.setLineWidth(0)
        self.confirmEmailPanel.setObjectName("confirmEmailPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.confirmEmailPanel)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_Title = QtWidgets.QVBoxLayout()
        self.verticalLayout_Title.setSpacing(6)
        self.verticalLayout_Title.setObjectName("verticalLayout_Title")
        self.logoIcon = QtWidgets.QLabel(parent=self.confirmEmailPanel)
        self.logoIcon.setMinimumSize(QtCore.QSize(80, 80))
        self.logoIcon.setMaximumSize(QtCore.QSize(80, 80))
        self.logoIcon.setStyleSheet("QLabel#logoIcon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    border-radius: 40px;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    font-size: 40px;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout_Title.addWidget(self.logoIcon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lableTitle = QtWidgets.QLabel(parent=self.confirmEmailPanel)
        self.lableTitle.setMinimumSize(QtCore.QSize(120, 35))
        self.lableTitle.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    background: transparent;\n"
"}")
        self.lableTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lableTitle.setObjectName("lableTitle")
        self.verticalLayout_Title.addWidget(self.lableTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelSubtitle = QtWidgets.QLabel(parent=self.confirmEmailPanel)
        self.labelSubtitle.setMinimumSize(QtCore.QSize(300, 40))
        self.labelSubtitle.setStyleSheet("QLabel#labelSubtitle{\n"
"    color: #666666;              /* gray color like HTML example */\n"
"    font-size: 12pt;              /* adjust size to fit QFrame */\n"
"    font-weight: normal;\n"
"    qproperty-alignment: \'AlignCenter\';   /* center text horizontally */\n"
"    margin-bottom: 14px;\n"
"    background: transparent;        \n"
"}\n"
"")
        self.labelSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSubtitle.setObjectName("labelSubtitle")
        self.verticalLayout_Title.addWidget(self.labelSubtitle)
        self.gridLayout_4.addLayout(self.verticalLayout_Title, 0, 0, 1, 1)
        self.verticalLayout_Buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_Buttons.setSpacing(10)
        self.verticalLayout_Buttons.setObjectName("verticalLayout_Buttons")
        self.buttonBackToCreateAccount = QtWidgets.QPushButton(parent=self.confirmEmailPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBackToCreateAccount.sizePolicy().hasHeightForWidth())
        self.buttonBackToCreateAccount.setSizePolicy(sizePolicy)
        self.buttonBackToCreateAccount.setMinimumSize(QtCore.QSize(200, 45))
        self.buttonBackToCreateAccount.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonBackToCreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonBackToCreateAccount.setTabletTracking(False)
        self.buttonBackToCreateAccount.setStyleSheet("QPushButton#buttonBackToCreateAccount {\n"
"    background: white;\n"
"    color: #667EEA;\n"
"    border: 2px solid #667EEA;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonBackToCreateAccount:hover {\n"
"    background: #f0f2ff;       /* light purple/blue tint */\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;       /* 3D lift effect */\n"
"}\n"
"\n"
"QPushButton#buttonBackToCreateAccount:pressed {\n"
"    background: #e0e4ff;       /* darker when pressed */\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;       /* pressed down effect */\n"
"}\n"
"")
        self.buttonBackToCreateAccount.setObjectName("buttonBackToCreateAccount")
        self.verticalLayout_Buttons.addWidget(self.buttonBackToCreateAccount, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.buttonBackToSignIn = QtWidgets.QPushButton(parent=self.confirmEmailPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBackToSignIn.sizePolicy().hasHeightForWidth())
        self.buttonBackToSignIn.setSizePolicy(sizePolicy)
        self.buttonBackToSignIn.setMinimumSize(QtCore.QSize(200, 45))
        self.buttonBackToSignIn.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonBackToSignIn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonBackToSignIn.setTabletTracking(False)
        self.buttonBackToSignIn.setStyleSheet("QPushButton#buttonBackToSignIn {\n"
"    background: white;\n"
"    color: #667EEA;\n"
"    border: 2px solid #667EEA;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonBackToSignIn:hover {\n"
"    background: #f0f2ff;       /* light purple/blue tint */\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;       /* 3D lift effect */\n"
"}\n"
"\n"
"QPushButton#buttonBackToSignIn:pressed {\n"
"    background: #e0e4ff;       /* darker when pressed */\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;       /* pressed down effect */\n"
"}\n"
"")
        self.buttonBackToSignIn.setObjectName("buttonBackToSignIn")
        self.verticalLayout_Buttons.addWidget(self.buttonBackToSignIn, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addLayout(self.verticalLayout_Buttons, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.gridLayout_4.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 5, 0, 1, 1)
        self.verticalLayout_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_input.setSpacing(5)
        self.verticalLayout_input.setObjectName("verticalLayout_input")
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_input.addItem(spacerItem2)
        self.buttonReSendCode = QtWidgets.QPushButton(parent=self.confirmEmailPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonReSendCode.sizePolicy().hasHeightForWidth())
        self.buttonReSendCode.setSizePolicy(sizePolicy)
        self.buttonReSendCode.setMinimumSize(QtCore.QSize(200, 45))
        self.buttonReSendCode.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonReSendCode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonReSendCode.setStyleSheet("QPushButton#buttonReSendCode {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #6A89E5, stop:1 #8A5CCF);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonReSendCode:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #5872C7, stop:1 #7547B8);\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton#buttonReSendCode:pressed {\n"
"    background: #4A5AA3;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"\n"
"QPushButton#buttonReSendCode:disabled {\n"
"    background: #AAAAAA;\n"
"    color: #666666;\n"
"    padding: 10px;\n"
"}")
        self.buttonReSendCode.setObjectName("buttonReSendCode")
        self.verticalLayout_input.addWidget(self.buttonReSendCode, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelTimer = QtWidgets.QLabel(parent=self.confirmEmailPanel)
        self.labelTimer.setStyleSheet("QLabel#labelTimer {\n"
"    background: transparent;\n"
"    color: #555;           /* soft gray, readable but not dominant */\n"
"    padding: 2px 4px;      /* small, compact */\n"
"    font-size: 9pt;        /* smaller text */\n"
"    font-weight: semi-bold;\n"
"    qproperty-alignment: AlignCenter;\n"
"}\n"
"QLabel#labelTimer[expired=\"true\"] {\n"
"    color: #2ECC71;   /* subtle green to indicate “ready” */\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.labelTimer.setObjectName("labelTimer")
        self.verticalLayout_input.addWidget(self.labelTimer)
        self.labelCode = QtWidgets.QLabel(parent=self.confirmEmailPanel)
        self.labelCode.setMinimumSize(QtCore.QSize(150, 45))
        self.labelCode.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelCode.setObjectName("labelCode")
        self.verticalLayout_input.addWidget(self.labelCode)
        self.lineEditVerificationCode = QtWidgets.QLineEdit(parent=self.confirmEmailPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditVerificationCode.sizePolicy().hasHeightForWidth())
        self.lineEditVerificationCode.setSizePolicy(sizePolicy)
        self.lineEditVerificationCode.setMinimumSize(QtCore.QSize(100, 40))
        self.lineEditVerificationCode.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditVerificationCode.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditVerificationCode.setInputMask("")
        self.lineEditVerificationCode.setMaxLength(6)
        self.lineEditVerificationCode.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditVerificationCode.setObjectName("lineEditVerificationCode")
        self.verticalLayout_input.addWidget(self.lineEditVerificationCode)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        self.verticalLayout_input.addItem(spacerItem3)
        self.buttonVerifyCode = QtWidgets.QPushButton(parent=self.confirmEmailPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonVerifyCode.sizePolicy().hasHeightForWidth())
        self.buttonVerifyCode.setSizePolicy(sizePolicy)
        self.buttonVerifyCode.setMinimumSize(QtCore.QSize(200, 45))
        self.buttonVerifyCode.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonVerifyCode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonVerifyCode.setStyleSheet("QPushButton#buttonVerifyCode {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #6A89E5, stop:1 #8A5CCF);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonVerifyCode:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #5872C7, stop:1 #7547B8);\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton#buttonVerifyCode:pressed {\n"
"    background: #4A5AA3;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.buttonVerifyCode.setObjectName("buttonVerifyCode")
        self.verticalLayout_input.addWidget(self.buttonVerifyCode, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addLayout(self.verticalLayout_input, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.confirmEmailPanel, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 1, 1, 1)

        self.retranslateUi(ConfirmEmailWidget)
        QtCore.QMetaObject.connectSlotsByName(ConfirmEmailWidget)

    def retranslateUi(self, ConfirmEmailWidget):
        _translate = QtCore.QCoreApplication.translate
        ConfirmEmailWidget.setWindowTitle(_translate("ConfirmEmailWidget", "Email Confirmation Window"))
        self.logoIcon.setText(_translate("ConfirmEmailWidget", "📩"))
        self.lableTitle.setText(_translate("ConfirmEmailWidget", "Confirm Email"))
        self.labelSubtitle.setText(_translate("ConfirmEmailWidget", "A code has been sent!"))
        self.buttonBackToCreateAccount.setText(_translate("ConfirmEmailWidget", "Back To Create Account"))
        self.buttonBackToSignIn.setText(_translate("ConfirmEmailWidget", "Back to Sign in"))
        self.buttonReSendCode.setText(_translate("ConfirmEmailWidget", "Re-Send Verification code"))
        self.labelTimer.setWhatsThis(_translate("ConfirmEmailWidget", "<html><head/><body><p>Timer before re-sending code again</p></body></html>"))
        self.labelTimer.setText(_translate("ConfirmEmailWidget", "60"))
        self.labelCode.setText(_translate("ConfirmEmailWidget", "Code"))
        self.lineEditVerificationCode.setPlaceholderText(_translate("ConfirmEmailWidget", "Enter 6-digits code sent to your email"))
        self.buttonVerifyCode.setText(_translate("ConfirmEmailWidget", "Verify"))
