# Form implementation generated from reading ui file 'create_admin_account_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAdminAccountWidget(object):
    def setupUi(self, CreateAdminAccountWidget):
        CreateAdminAccountWidget.setObjectName("CreateAdminAccountWidget")
        CreateAdminAccountWidget.resize(600, 800)
        CreateAdminAccountWidget.setMinimumSize(QtCore.QSize(0, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qrc_images/assets/images/login_bg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CreateAdminAccountWidget.setWindowIcon(icon)
        CreateAdminAccountWidget.setStyleSheet("background: qlineargradient(\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:1,\n"
"    stop:0 #f093fb,\n"
"    stop:1 #f5576c\n"
");\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(CreateAdminAccountWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.loginPanel = QtWidgets.QFrame(parent=CreateAdminAccountWidget)
        self.loginPanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPanel.sizePolicy().hasHeightForWidth())
        self.loginPanel.setSizePolicy(sizePolicy)
        self.loginPanel.setMinimumSize(QtCore.QSize(400, 0))
        self.loginPanel.setMaximumSize(QtCore.QSize(650, 1000))
        self.loginPanel.setStyleSheet("QFrame#loginPanel {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"    padding: 30px;\n"
"}\n"
"")
        self.loginPanel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.loginPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginPanel.setLineWidth(0)
        self.loginPanel.setObjectName("loginPanel")
        self.gridLayout = QtWidgets.QGridLayout(self.loginPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollAreaCreateAcc = QtWidgets.QScrollArea(parent=self.loginPanel)
        self.scrollAreaCreateAcc.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaCreateAcc.setStyleSheet("/* ===== ScrollArea Transparent Background ===== */\n"
"QScrollArea#scrollAreaCreateAcc {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding-right: 3px; /* leaves space for the scrollbar to appear offset */\n"
"}\n"
"\n"
"QScrollArea#scrollAreaCreateAcc > QWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea#scrollAreaCreateAcc > QWidget > QWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollAreaCreateAcc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollAreaCreateAcc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollAreaCreateAcc.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollAreaCreateAcc.setWidgetResizable(True)
        self.scrollAreaCreateAcc.setObjectName("scrollAreaCreateAcc")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -19, 343, 802))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_Title = QtWidgets.QVBoxLayout()
        self.verticalLayout_Title.setSpacing(6)
        self.verticalLayout_Title.setObjectName("verticalLayout_Title")
        self.logoIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logoIcon.setMinimumSize(QtCore.QSize(80, 80))
        self.logoIcon.setMaximumSize(QtCore.QSize(80, 80))
        self.logoIcon.setStyleSheet("QLabel#logoIcon {\n"
"    background: qlineargradient(\n"
"    x1:0, y1:0,\n"
"    x2:1, y2:1,\n"
"    stop:0 #f093fb,\n"
"    stop:1 #f5576c\n"
");\n"
"\n"
"    border-radius: 40px;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    font-size: 40px;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout_Title.addWidget(self.logoIcon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lableTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.lableTitle.setMinimumSize(QtCore.QSize(120, 35))
        self.lableTitle.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    background: transparent;\n"
"}")
        self.lableTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lableTitle.setObjectName("lableTitle")
        self.verticalLayout_Title.addWidget(self.lableTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelSubtitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelSubtitle.setMinimumSize(QtCore.QSize(300, 40))
        self.labelSubtitle.setStyleSheet("QLabel#labelSubtitle{\n"
"    color: #666666;              /* gray color like HTML example */\n"
"    font-size: 12pt;              /* adjust size to fit QFrame */\n"
"    font-weight: normal;\n"
"    qproperty-alignment: \'AlignCenter\';   /* center text horizontally */\n"
"    margin-bottom: 14px;          \n"
"    background: transparent;\n"
"}\n"
"")
        self.labelSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSubtitle.setObjectName("labelSubtitle")
        self.verticalLayout_Title.addWidget(self.labelSubtitle)
        self.verticalLayout_5.addLayout(self.verticalLayout_Title)
        self.verticalLayout_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_input.setSpacing(5)
        self.verticalLayout_input.setObjectName("verticalLayout_input")
        self.labelFullName = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelFullName.setMinimumSize(QtCore.QSize(150, 45))
        self.labelFullName.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelFullName.setObjectName("labelFullName")
        self.verticalLayout_input.addWidget(self.labelFullName)
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFullName.sizePolicy().hasHeightForWidth())
        self.lineEditFullName.setSizePolicy(sizePolicy)
        self.lineEditFullName.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditFullName.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditFullName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditFullName.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.verticalLayout_input.addWidget(self.lineEditFullName)
        self.labelEmail = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelEmail.setMinimumSize(QtCore.QSize(150, 45))
        self.labelEmail.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelEmail.setObjectName("labelEmail")
        self.verticalLayout_input.addWidget(self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEmail.sizePolicy().hasHeightForWidth())
        self.lineEditEmail.setSizePolicy(sizePolicy)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditEmail.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditEmail.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout_input.addWidget(self.lineEditEmail)
        self.labelPassword = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPassword.setMinimumSize(QtCore.QSize(150, 45))
        self.labelPassword.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_input.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_input.addWidget(self.lineEditPassword)
        self.progressBarPwrdStrength = QtWidgets.QProgressBar(parent=self.scrollAreaWidgetContents)
        self.progressBarPwrdStrength.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBarPwrdStrength.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        self.progressBarPwrdStrength.setFont(font)
        self.progressBarPwrdStrength.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;       /* thin border */\n"
"    border-radius: 5px;           /* rounded corners */\n"
"    text-align: center;\n"
"    height: 12px;                  /* slim height */\n"
"    background-color: #f0f0f0;    /* light gray background */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    /* background-color will be overridden dynamically for password strength */\n"
"}")
        self.progressBarPwrdStrength.setProperty("value", 24)
        self.progressBarPwrdStrength.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBarPwrdStrength.setInvertedAppearance(False)
        self.progressBarPwrdStrength.setObjectName("progressBarPwrdStrength")
        self.verticalLayout_input.addWidget(self.progressBarPwrdStrength)
        self.labelPwrdStrengthStatus = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPwrdStrengthStatus.setStyleSheet("QLabel#labelPwrdStrengthStatus {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #555555;  /* Default text color */\n"
"    padding-top: -4px;\n"
"    padding-bottom: 2px;\n"
"    background: transparent;\n"
"}")
        self.labelPwrdStrengthStatus.setObjectName("labelPwrdStrengthStatus")
        self.verticalLayout_input.addWidget(self.labelPwrdStrengthStatus)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background: transparent")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 321, 68))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelPasswordRules = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPasswordRules.sizePolicy().hasHeightForWidth())
        self.labelPasswordRules.setSizePolicy(sizePolicy)
        self.labelPasswordRules.setStyleSheet("    background: transparent;")
        self.labelPasswordRules.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.labelPasswordRules.setWordWrap(True)
        self.labelPasswordRules.setObjectName("labelPasswordRules")
        self.verticalLayout_4.addWidget(self.labelPasswordRules)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_input.addWidget(self.scrollArea)
        self.labelPasswordConfirm = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPasswordConfirm.setMinimumSize(QtCore.QSize(150, 45))
        self.labelPasswordConfirm.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelPasswordConfirm.setObjectName("labelPasswordConfirm")
        self.verticalLayout_input.addWidget(self.labelPasswordConfirm)
        self.lineEditPasswordConfirm = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPasswordConfirm.sizePolicy().hasHeightForWidth())
        self.lineEditPasswordConfirm.setSizePolicy(sizePolicy)
        self.lineEditPasswordConfirm.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditPasswordConfirm.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditPasswordConfirm.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"QLineEdit[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}\n"
"")
        self.lineEditPasswordConfirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPasswordConfirm.setObjectName("lineEditPasswordConfirm")
        self.verticalLayout_input.addWidget(self.lineEditPasswordConfirm)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_input.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.verticalLayout_input)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelGeneralStatus = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelGeneralStatus.setStyleSheet("QLabel#labelGeneralStatus {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #555555;  /* Default text color */\n"
"    padding-top: -4px;\n"
"    padding-bottom: 2px;\n"
"    background: white;\n"
"}\n"
"/* When property \'statusColor\' is set, override color */\n"
"QLabel#labelGeneralStatus[statusColor=\"red\"] {\n"
"    color: red;\n"
"}\n"
"QLabel#labelGeneralStatus[statusColor=\"green\"] {\n"
"    color: green;\n"
"}")
        self.labelGeneralStatus.setObjectName("labelGeneralStatus")
        self.verticalLayout.addWidget(self.labelGeneralStatus, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.buttonCreateAccount = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCreateAccount.sizePolicy().hasHeightForWidth())
        self.buttonCreateAccount.setSizePolicy(sizePolicy)
        self.buttonCreateAccount.setMinimumSize(QtCore.QSize(220, 45))
        self.buttonCreateAccount.setMaximumSize(QtCore.QSize(220, 55))
        self.buttonCreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCreateAccount.setStyleSheet("QPushButton#buttonCreateAccount {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #4F63C6, stop:1 #5D3F9E);\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:pressed {\n"
"    background: #3C4A99;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"QPushButton#buttonCreateAccount:disabled {\n"
"    background: #AAAAAA;\n"
"    color: #666666;\n"
"    padding: 10px;\n"
"}")
        self.buttonCreateAccount.setObjectName("buttonCreateAccount")
        self.verticalLayout.addWidget(self.buttonCreateAccount, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.scrollAreaCreateAcc.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollAreaCreateAcc, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.loginPanel, 1, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 2, 1, 1, 1)

        self.retranslateUi(CreateAdminAccountWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateAdminAccountWidget)

    def retranslateUi(self, CreateAdminAccountWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateAdminAccountWidget.setWindowTitle(_translate("CreateAdminAccountWidget", "Create New Account"))
        self.logoIcon.setText(_translate("CreateAdminAccountWidget", "🌟"))
        self.lableTitle.setText(_translate("CreateAdminAccountWidget", "New Admin"))
        self.labelSubtitle.setText(_translate("CreateAdminAccountWidget", "Qucik Registration"))
        self.labelFullName.setText(_translate("CreateAdminAccountWidget", "<html><head/><body><p>Full Name (First, Father, Family) <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditFullName.setPlaceholderText(_translate("CreateAdminAccountWidget", "Salem Ahmad Saleh"))
        self.labelEmail.setText(_translate("CreateAdminAccountWidget", "<html><head/><body><p>Email <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditEmail.setPlaceholderText(_translate("CreateAdminAccountWidget", "yasser@example.com"))
        self.labelPassword.setText(_translate("CreateAdminAccountWidget", "Password <font color=\"red\">*</font>"))
        self.lineEditPassword.setToolTip(_translate("CreateAdminAccountWidget", "<html><head/><body><p>Password requirements:</p><p>• Minimum 8 characters</p><p>• At least 1 uppercase letter (A-Z)</p><p>• At least 1 lowercase letter (a-z)</p><p>• At least 1 number (0-9)</p><p>• At least 1 special character (= _ / \\ + ! @ # $ % ^ &amp; * ( ) , . ? &quot; : { } | &lt; &gt; -)</p></body></html>"))
        self.lineEditPassword.setPlaceholderText(_translate("CreateAdminAccountWidget", "Min. 8 characters"))
        self.progressBarPwrdStrength.setFormat(_translate("CreateAdminAccountWidget", "Password strength: %p%"))
        self.labelPwrdStrengthStatus.setText(_translate("CreateAdminAccountWidget", "Password Status"))
        self.labelPasswordRules.setText(_translate("CreateAdminAccountWidget", "<html><head/><body><p><span style=\" color:#ff0000;\">• Password requirements will appear here</span></p></body></html>"))
        self.labelPasswordConfirm.setText(_translate("CreateAdminAccountWidget", "<html><head/><body><p>Confrim Password <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditPasswordConfirm.setPlaceholderText(_translate("CreateAdminAccountWidget", "Re-enter password"))
        self.labelGeneralStatus.setText(_translate("CreateAdminAccountWidget", "General Status"))
        self.buttonCreateAccount.setText(_translate("CreateAdminAccountWidget", "Create  Account"))
