# Form implementation generated from reading ui file 'create_account_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CreateAccountWidget(object):
    def setupUi(self, CreateAccountWidget):
        CreateAccountWidget.setObjectName("CreateAccountWidget")
        CreateAccountWidget.resize(600, 800)
        CreateAccountWidget.setMinimumSize(QtCore.QSize(0, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qrc_images/assets/images/login_bg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CreateAccountWidget.setWindowIcon(icon)
        CreateAccountWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget#CreateAccountWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(CreateAccountWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.loginPanel = QtWidgets.QFrame(parent=CreateAccountWidget)
        self.loginPanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPanel.sizePolicy().hasHeightForWidth())
        self.loginPanel.setSizePolicy(sizePolicy)
        self.loginPanel.setMinimumSize(QtCore.QSize(400, 0))
        self.loginPanel.setMaximumSize(QtCore.QSize(650, 1000))
        self.loginPanel.setStyleSheet("QFrame#loginPanel {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"    padding: 30px;\n"
"}\n"
"")
        self.loginPanel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.loginPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginPanel.setLineWidth(0)
        self.loginPanel.setObjectName("loginPanel")
        self.gridLayout = QtWidgets.QGridLayout(self.loginPanel)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollAreaCreateAcc = QtWidgets.QScrollArea(parent=self.loginPanel)
        self.scrollAreaCreateAcc.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaCreateAcc.setStyleSheet("/* ===== ScrollArea Transparent Background ===== */\n"
"QScrollArea#scrollAreaCreateAcc {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding-right: 3px; /* leaves space for the scrollbar to appear offset */\n"
"}\n"
"\n"
"QScrollArea#scrollAreaCreateAcc > QWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"QScrollArea#scrollAreaCreateAcc > QWidget > QWidget {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollAreaCreateAcc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollAreaCreateAcc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.scrollAreaCreateAcc.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollAreaCreateAcc.setWidgetResizable(True)
        self.scrollAreaCreateAcc.setObjectName("scrollAreaCreateAcc")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -253, 343, 946))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_Title = QtWidgets.QVBoxLayout()
        self.verticalLayout_Title.setSpacing(6)
        self.verticalLayout_Title.setObjectName("verticalLayout_Title")
        self.logoIcon = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.logoIcon.setMinimumSize(QtCore.QSize(80, 80))
        self.logoIcon.setMaximumSize(QtCore.QSize(80, 80))
        self.logoIcon.setStyleSheet("QLabel#logoIcon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    border-radius: 40px;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    font-size: 40px;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout_Title.addWidget(self.logoIcon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lableTitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.lableTitle.setMinimumSize(QtCore.QSize(120, 35))
        self.lableTitle.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    background: transparent;\n"
"}")
        self.lableTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lableTitle.setObjectName("lableTitle")
        self.verticalLayout_Title.addWidget(self.lableTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelSubtitle = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelSubtitle.setMinimumSize(QtCore.QSize(300, 40))
        self.labelSubtitle.setStyleSheet("QLabel#labelSubtitle{\n"
"    color: #666666;              /* gray color like HTML example */\n"
"    font-size: 12pt;              /* adjust size to fit QFrame */\n"
"    font-weight: normal;\n"
"    qproperty-alignment: \'AlignCenter\';   /* center text horizontally */\n"
"    margin-bottom: 14px;          \n"
"    background: transparent;\n"
"}\n"
"")
        self.labelSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSubtitle.setObjectName("labelSubtitle")
        self.verticalLayout_Title.addWidget(self.labelSubtitle)
        self.verticalLayout_5.addLayout(self.verticalLayout_Title)
        self.verticalLayout_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_input.setSpacing(5)
        self.verticalLayout_input.setObjectName("verticalLayout_input")
        self.labelFullName = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelFullName.setMinimumSize(QtCore.QSize(150, 45))
        self.labelFullName.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelFullName.setObjectName("labelFullName")
        self.verticalLayout_input.addWidget(self.labelFullName)
        self.lineEditFullName = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFullName.sizePolicy().hasHeightForWidth())
        self.lineEditFullName.setSizePolicy(sizePolicy)
        self.lineEditFullName.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditFullName.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditFullName.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditFullName.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.verticalLayout_input.addWidget(self.lineEditFullName)
        self.labelEmail = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelEmail.setMinimumSize(QtCore.QSize(150, 45))
        self.labelEmail.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelEmail.setObjectName("labelEmail")
        self.verticalLayout_input.addWidget(self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditEmail.sizePolicy().hasHeightForWidth())
        self.lineEditEmail.setSizePolicy(sizePolicy)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditEmail.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditEmail.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout_input.addWidget(self.lineEditEmail)
        self.labelProgram = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelProgram.setMinimumSize(QtCore.QSize(150, 45))
        self.labelProgram.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelProgram.setObjectName("labelProgram")
        self.verticalLayout_input.addWidget(self.labelProgram)
        self.comboBoxSelectProgram = QtWidgets.QComboBox(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSelectProgram.sizePolicy().hasHeightForWidth())
        self.comboBoxSelectProgram.setSizePolicy(sizePolicy)
        self.comboBoxSelectProgram.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBoxSelectProgram.setMaximumSize(QtCore.QSize(16777215, 65))
        self.comboBoxSelectProgram.setStyleSheet("/* ----------------- QComboBox Base ----------------- */\n"
"QComboBox {\n"
"    border: 2px solid #E0E0E0;          /* main border */\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                   /* Matches QLineEdit padding */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"}\n"
"\n"
"/* Focused state */\n"
"QComboBox:focus {\n"
"    border: 2px solid #667EEA; \n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* ----------------- Drop-down Arrow ----------------- */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-width: 1px;\n"
"    border-left-color: #E0E0E0;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 12px;       /* rounder corners */\n"
"    border-bottom-right-radius: 12px;    /* rounder corners */\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove ugly black border on hover/focus */\n"
"QComboBox::drop-down:hover,\n"
"QComboBox::drop-down:focus {\n"
"    border-left-color: #667EEA;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Modern, visible arrow using simple chevron */\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: solid #667EEA;\n"
"    border-width: 0 2px 2px 0;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"/* ----------------- Dropdown Popup ----------------- */\n"
"/* Dropdown Popup */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fdfdfd;          /* slightly off-white */\n"
"    border: 2px solid #E0E0E0;          /* subtle grey border */\n"
"    border-radius: 8px;                  /* may not be perfect on Windows */\n"
"    color: #111111;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"    selection-background-color: #667EEA;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items hover/selection */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(102, 126, 234, 0.1);\n"
"    color: #111111;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #667EEA;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Error highlight for combo box */\n"
"QComboBox[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}")
        self.comboBoxSelectProgram.setObjectName("comboBoxSelectProgram")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.comboBoxSelectProgram.addItem("")
        self.verticalLayout_input.addWidget(self.comboBoxSelectProgram)
        self.labelPassword = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPassword.setMinimumSize(QtCore.QSize(150, 45))
        self.labelPassword.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_input.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_input.addWidget(self.lineEditPassword)
        self.progressBarPwrdStrength = QtWidgets.QProgressBar(parent=self.scrollAreaWidgetContents)
        self.progressBarPwrdStrength.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBarPwrdStrength.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(5)
        font.setBold(True)
        self.progressBarPwrdStrength.setFont(font)
        self.progressBarPwrdStrength.setStyleSheet("QProgressBar {\n"
"    border: 1px solid #ccc;       /* thin border */\n"
"    border-radius: 5px;           /* rounded corners */\n"
"    text-align: center;\n"
"    height: 12px;                  /* slim height */\n"
"    background-color: #f0f0f0;    /* light gray background */\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 5px;\n"
"    /* background-color will be overridden dynamically for password strength */\n"
"}")
        self.progressBarPwrdStrength.setProperty("value", 24)
        self.progressBarPwrdStrength.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.progressBarPwrdStrength.setInvertedAppearance(False)
        self.progressBarPwrdStrength.setObjectName("progressBarPwrdStrength")
        self.verticalLayout_input.addWidget(self.progressBarPwrdStrength)
        self.labelPwrdStrengthStatus = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPwrdStrengthStatus.setStyleSheet("QLabel#labelPwrdStrengthStatus {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #555555;  /* Default text color */\n"
"    padding-top: -4px;\n"
"    padding-bottom: 2px;\n"
"    background: transparent;\n"
"}")
        self.labelPwrdStrengthStatus.setObjectName("labelPwrdStrengthStatus")
        self.verticalLayout_input.addWidget(self.labelPwrdStrengthStatus)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet("background: transparent")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 321, 68))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelPasswordRules = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelPasswordRules.sizePolicy().hasHeightForWidth())
        self.labelPasswordRules.setSizePolicy(sizePolicy)
        self.labelPasswordRules.setStyleSheet("    background: transparent;")
        self.labelPasswordRules.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.labelPasswordRules.setWordWrap(True)
        self.labelPasswordRules.setObjectName("labelPasswordRules")
        self.verticalLayout_4.addWidget(self.labelPasswordRules)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_input.addWidget(self.scrollArea)
        self.labelPasswordConfirm = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelPasswordConfirm.setMinimumSize(QtCore.QSize(150, 45))
        self.labelPasswordConfirm.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelPasswordConfirm.setObjectName("labelPasswordConfirm")
        self.verticalLayout_input.addWidget(self.labelPasswordConfirm)
        self.lineEditPasswordConfirm = QtWidgets.QLineEdit(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPasswordConfirm.sizePolicy().hasHeightForWidth())
        self.lineEditPasswordConfirm.setSizePolicy(sizePolicy)
        self.lineEditPasswordConfirm.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditPasswordConfirm.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditPasswordConfirm.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"QLineEdit[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}\n"
"")
        self.lineEditPasswordConfirm.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPasswordConfirm.setObjectName("lineEditPasswordConfirm")
        self.verticalLayout_input.addWidget(self.lineEditPasswordConfirm)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        self.verticalLayout_input.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.verticalLayout_input)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelGeneralStatus = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.labelGeneralStatus.setStyleSheet("QLabel#labelGeneralStatus {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #555555;  /* Default text color */\n"
"    padding-top: -4px;\n"
"    padding-bottom: 2px;\n"
"    background: white;\n"
"}\n"
"/* When property \'statusColor\' is set, override color */\n"
"QLabel#labelGeneralStatus[statusColor=\"red\"] {\n"
"    color: red;\n"
"}\n"
"QLabel#labelGeneralStatus[statusColor=\"green\"] {\n"
"    color: green;\n"
"}")
        self.labelGeneralStatus.setObjectName("labelGeneralStatus")
        self.verticalLayout.addWidget(self.labelGeneralStatus, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.buttonCreateAccount = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCreateAccount.sizePolicy().hasHeightForWidth())
        self.buttonCreateAccount.setSizePolicy(sizePolicy)
        self.buttonCreateAccount.setMinimumSize(QtCore.QSize(220, 45))
        self.buttonCreateAccount.setMaximumSize(QtCore.QSize(220, 55))
        self.buttonCreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCreateAccount.setStyleSheet("QPushButton#buttonCreateAccount {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #4F63C6, stop:1 #5D3F9E);\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:pressed {\n"
"    background: #3C4A99;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"QPushButton#buttonCreateAccount:disabled {\n"
"    background: #AAAAAA;\n"
"    color: #666666;\n"
"    padding: 10px;\n"
"}")
        self.buttonCreateAccount.setObjectName("buttonCreateAccount")
        self.verticalLayout.addWidget(self.buttonCreateAccount, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.accountLoginFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountLoginFrame.sizePolicy().hasHeightForWidth())
        self.accountLoginFrame.setSizePolicy(sizePolicy)
        self.accountLoginFrame.setMinimumSize(QtCore.QSize(0, 30))
        self.accountLoginFrame.setStyleSheet("QFrame#accountLoginFrame {\n"
"    background: transparent;\n"
"    border: none;   /* remove any borders if present */\n"
"}\n"
"")
        self.accountLoginFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.accountLoginFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.accountLoginFrame.setObjectName("accountLoginFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.accountLoginFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.labelHaveAccount = QtWidgets.QLabel(parent=self.accountLoginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.labelHaveAccount.sizePolicy().hasHeightForWidth())
        self.labelHaveAccount.setSizePolicy(sizePolicy)
        self.labelHaveAccount.setStyleSheet("QLabel#labelHaveAccount {\n"
"    color: #555555;\n"
"    font: 12pt \"Segoe UI\";\n"
"    margin-left: 14px;  /* Move the whole label slightly right */\n"
"    background-color: white\n"
"}")
        self.labelHaveAccount.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelHaveAccount.setOpenExternalLinks(False)
        self.labelHaveAccount.setObjectName("labelHaveAccount")
        self.horizontalLayout.addWidget(self.labelHaveAccount)
        self.buttonLoginHere = QtWidgets.QPushButton(parent=self.accountLoginFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.buttonLoginHere.sizePolicy().hasHeightForWidth())
        self.buttonLoginHere.setSizePolicy(sizePolicy)
        self.buttonLoginHere.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonLoginHere.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.buttonLoginHere.setStyleSheet("QPushButton#buttonLoginHere {\n"
"    color: #667EEA;                /* Calm blue tone */\n"
"    background: transparent;\n"
"    border: none;\n"
"    font: 12pt \"Segoe UI\";\n"
"    text-decoration: underline;\n"
"    padding-left: 3px;             /* a bit of space between text */\n"
"}\n"
"\n"
"QPushButton#buttonLoginHere:hover {\n"
"    color: #4F63C6;\n"
"}\n"
"\n"
"QPushButton#buttonLoginHere:pressed {\n"
"    color: #3C4A9A;                /* slightly darker for pressed effect */\n"
"    padding-left: 5px;             /* subtle “move” effect to feel pressed */\n"
"    padding-top: 2px;\n"
"}\n"
"")
        self.buttonLoginHere.setObjectName("buttonLoginHere")
        self.horizontalLayout.addWidget(self.buttonLoginHere)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.accountLoginFrame)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_5.addItem(spacerItem7)
        self.scrollAreaCreateAcc.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollAreaCreateAcc, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.loginPanel, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 2, 1, 1, 1)

        self.retranslateUi(CreateAccountWidget)
        QtCore.QMetaObject.connectSlotsByName(CreateAccountWidget)

    def retranslateUi(self, CreateAccountWidget):
        _translate = QtCore.QCoreApplication.translate
        CreateAccountWidget.setWindowTitle(_translate("CreateAccountWidget", "Create New Account"))
        self.logoIcon.setText(_translate("CreateAccountWidget", "🌟"))
        self.lableTitle.setText(_translate("CreateAccountWidget", "New Student"))
        self.labelSubtitle.setText(_translate("CreateAccountWidget", "Qucik Registration"))
        self.labelFullName.setText(_translate("CreateAccountWidget", "<html><head/><body><p>Full Name (First, Father, Family) <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditFullName.setPlaceholderText(_translate("CreateAccountWidget", "Salem Ahmad Saleh"))
        self.labelEmail.setText(_translate("CreateAccountWidget", "<html><head/><body><p>Email <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditEmail.setPlaceholderText(_translate("CreateAccountWidget", "yasser@example.com"))
        self.labelProgram.setText(_translate("CreateAccountWidget", "<html><head/><body><p>Program <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.comboBoxSelectProgram.setPlaceholderText(_translate("CreateAccountWidget", "Select"))
        self.comboBoxSelectProgram.setItemText(0, _translate("CreateAccountWidget", "Select..."))
        self.comboBoxSelectProgram.setItemText(1, _translate("CreateAccountWidget", "Computer"))
        self.comboBoxSelectProgram.setItemText(2, _translate("CreateAccountWidget", "Communication"))
        self.comboBoxSelectProgram.setItemText(3, _translate("CreateAccountWidget", "Power"))
        self.comboBoxSelectProgram.setItemText(4, _translate("CreateAccountWidget", "Biomedical"))
        self.labelPassword.setText(_translate("CreateAccountWidget", "Password <font color=\"red\">*</font>"))
        self.lineEditPassword.setToolTip(_translate("CreateAccountWidget", "<html><head/><body><p>Password requirements:</p><p>• Minimum 8 characters</p><p>• At least 1 uppercase letter (A-Z)</p><p>• At least 1 lowercase letter (a-z)</p><p>• At least 1 number (0-9)</p><p>• At least 1 special character (= _ / \\ + ! @ # $ % ^ &amp; * ( ) , . ? &quot; : { } | &lt; &gt; -)</p></body></html>"))
        self.lineEditPassword.setPlaceholderText(_translate("CreateAccountWidget", "Min. 8 characters"))
        self.progressBarPwrdStrength.setFormat(_translate("CreateAccountWidget", "Password strength: %p%"))
        self.labelPwrdStrengthStatus.setText(_translate("CreateAccountWidget", "Password Status"))
        self.labelPasswordRules.setText(_translate("CreateAccountWidget", "<html><head/><body><p><span style=\" color:#ff0000;\">• Password requirements will appear here</span></p></body></html>"))
        self.labelPasswordConfirm.setText(_translate("CreateAccountWidget", "<html><head/><body><p>Confrim Password <span style=\" color:#ff0000;\">*</span></p></body></html>"))
        self.lineEditPasswordConfirm.setPlaceholderText(_translate("CreateAccountWidget", "Re-enter password"))
        self.labelGeneralStatus.setText(_translate("CreateAccountWidget", "General Status"))
        self.buttonCreateAccount.setText(_translate("CreateAccountWidget", "Create  Account"))
        self.labelHaveAccount.setText(_translate("CreateAccountWidget", "Have an Account?"))
        self.buttonLoginHere.setText(_translate("CreateAccountWidget", "Login Here"))
