# Form implementation generated from reading ui file 'login_widget.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWidget(object):
    def setupUi(self, LoginWidget):
        LoginWidget.setObjectName("LoginWidget")
        LoginWidget.resize(600, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/qrc_images/assets/images/login_bg.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LoginWidget.setWindowIcon(icon)
        LoginWidget.setStyleSheet("/* ===== Background Gradient ===== */\n"
"QWidget#LoginWidget {\n"
"    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 1, y2: 1,\n"
"        stop: 0 #667EEA,\n"
"        stop: 1 #764BA2\n"
"    );\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(LoginWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.loginPanel = QtWidgets.QFrame(parent=LoginWidget)
        self.loginPanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginPanel.sizePolicy().hasHeightForWidth())
        self.loginPanel.setSizePolicy(sizePolicy)
        self.loginPanel.setMinimumSize(QtCore.QSize(385, 0))
        self.loginPanel.setMaximumSize(QtCore.QSize(650, 750))
        self.loginPanel.setStyleSheet("QFrame#loginPanel {\n"
"    background-color: #ffffff;\n"
"    border-radius: 20px;\n"
"    padding: 30px;\n"
"}\n"
"")
        self.loginPanel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.loginPanel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.loginPanel.setLineWidth(0)
        self.loginPanel.setObjectName("loginPanel")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.loginPanel)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_Title = QtWidgets.QVBoxLayout()
        self.verticalLayout_Title.setSpacing(6)
        self.verticalLayout_Title.setObjectName("verticalLayout_Title")
        self.logoIcon = QtWidgets.QLabel(parent=self.loginPanel)
        self.logoIcon.setMinimumSize(QtCore.QSize(80, 80))
        self.logoIcon.setMaximumSize(QtCore.QSize(80, 80))
        self.logoIcon.setStyleSheet("QLabel#logoIcon {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    border-radius: 40px;\n"
"    min-width: 80px;\n"
"    min-height: 80px;\n"
"    max-width: 80px;\n"
"    max-height: 80px;\n"
"    font-size: 40px;\n"
"    color: white;\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}\n"
"")
        self.logoIcon.setObjectName("logoIcon")
        self.verticalLayout_Title.addWidget(self.logoIcon, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lableTitle = QtWidgets.QLabel(parent=self.loginPanel)
        self.lableTitle.setMinimumSize(QtCore.QSize(120, 35))
        self.lableTitle.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"    text-align: center;\n"
"    background: transparent;\n"
"}")
        self.lableTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lableTitle.setObjectName("lableTitle")
        self.verticalLayout_Title.addWidget(self.lableTitle, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.labelSubtitle = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelSubtitle.setMinimumSize(QtCore.QSize(300, 40))
        self.labelSubtitle.setStyleSheet("QLabel#labelSubtitle{\n"
"    color: #666666;              /* gray color like HTML example */\n"
"    font-size: 12pt;              /* adjust size to fit QFrame */\n"
"    font-weight: normal;\n"
"    qproperty-alignment: \'AlignCenter\';   /* center text horizontally */\n"
"    margin-bottom: 14px;\n"
"    background: transparent;        \n"
"}\n"
"")
        self.labelSubtitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelSubtitle.setObjectName("labelSubtitle")
        self.verticalLayout_Title.addWidget(self.labelSubtitle)
        self.gridLayout_4.addLayout(self.verticalLayout_Title, 0, 0, 1, 1)
        self.verticalLayout_input = QtWidgets.QVBoxLayout()
        self.verticalLayout_input.setSpacing(5)
        self.verticalLayout_input.setObjectName("verticalLayout_input")
        self.labelUsername = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelUsername.setMinimumSize(QtCore.QSize(150, 45))
        self.labelUsername.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelUsername.setObjectName("labelUsername")
        self.verticalLayout_input.addWidget(self.labelUsername)
        self.lineEditUsername = QtWidgets.QLineEdit(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditUsername.sizePolicy().hasHeightForWidth())
        self.lineEditUsername.setSizePolicy(sizePolicy)
        self.lineEditUsername.setMinimumSize(QtCore.QSize(100, 35))
        self.lineEditUsername.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditUsername.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditUsername.setObjectName("lineEditUsername")
        self.verticalLayout_input.addWidget(self.lineEditUsername)
        self.labelPassword = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelPassword.setMinimumSize(QtCore.QSize(150, 45))
        self.labelPassword.setStyleSheet("QLabel {\n"
"    color: #333333;\n"
"    font-size: 13pt;\n"
"    margin-top: 10px;\n"
"    margin-bottom: 4px;\n"
"    background: transparent;\n"
"}")
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout_input.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditPassword.sizePolicy().hasHeightForWidth())
        self.lineEditPassword.setSizePolicy(sizePolicy)
        self.lineEditPassword.setMinimumSize(QtCore.QSize(80, 35))
        self.lineEditPassword.setMaximumSize(QtCore.QSize(16777215, 65))
        self.lineEditPassword.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #E0E0E0;\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;\n"
"    background: rgba(250, 250, 250, 200); /* slightly transparent soft white */\n"
"    font-size: 11pt;\n"
"    color: #111111;                         /* user text color */\n"
"    font-style: normal;                      /* ensures user text is not italic */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #667EEA;\n"
"    background: rgba(250, 250, 250, 220);   /* slightly brighter on focus */\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: rgba(50, 50, 50, 200);           /* placeholder text color */\n"
"    font-style: italic;                      /* placeholder remains italic */\n"
"}\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.verticalLayout_input.addWidget(self.lineEditPassword)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_input.addItem(spacerItem)
        self.horizontalLayout_RememberReset = QtWidgets.QHBoxLayout()
        self.horizontalLayout_RememberReset.setSpacing(13)
        self.horizontalLayout_RememberReset.setObjectName("horizontalLayout_RememberReset")
        self.horizontalLayout_Remember = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Remember.setSpacing(5)
        self.horizontalLayout_Remember.setObjectName("horizontalLayout_Remember")
        self.checkBoxRemember = QtWidgets.QCheckBox(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxRemember.sizePolicy().hasHeightForWidth())
        self.checkBoxRemember.setSizePolicy(sizePolicy)
        self.checkBoxRemember.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBoxRemember.setStyleSheet("QCheckBox#checkBoxRemember {\n"
"    spacing: 8px;  /* space between box and text */\n"
"    color: #333333; /* text color */\n"
"    font-size: 11pt;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Customize the box itself */\n"
"QCheckBox#checkBoxRemember::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px; /* rounded corners */\n"
"    border: 2px solid #E0E0E0;\n"
"    background: #FAFAFA;\n"
"}\n"
"\n"
"/* Hover effect */\n"
"QCheckBox#checkBoxRemember::indicator:hover {\n"
"    border: 2px solid #667EEA;\n"
"}\n"
"\n"
"/* Checked state */\n"
"QCheckBox#checkBoxRemember::indicator:checked {\n"
"    background: #667EEA;\n"
"    border: 2px solid #667EEA;\n"
"}\n"
"")
        self.checkBoxRemember.setText("")
        self.checkBoxRemember.setObjectName("checkBoxRemember")
        self.horizontalLayout_Remember.addWidget(self.checkBoxRemember)
        self.labelRemember = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelRemember.setStyleSheet("QLabel#labelRemember{\n"
"    color: #333333;           /* matches your other labels */\n"
"    font-size: 11pt;           /* slightly smaller than input labels */\n"
"    font-weight: 500;\n"
"    background: transparent;\n"
"}\n"
"")
        self.labelRemember.setObjectName("labelRemember")
        self.horizontalLayout_Remember.addWidget(self.labelRemember, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.horizontalLayout_RememberReset.addLayout(self.horizontalLayout_Remember)
        self.horizontalLayout_ResetPwrd = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ResetPwrd.setSpacing(2)
        self.horizontalLayout_ResetPwrd.setObjectName("horizontalLayout_ResetPwrd")
        self.labelForgotPassword = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelForgotPassword.setMinimumSize(QtCore.QSize(110, 30))
        self.labelForgotPassword.setStyleSheet("QLabel#labelForgotPassword {\n"
"    color: #777;\n"
"    font-size: 10pt;\n"
"    font-family: \'Segoe UI\';\n"
"    qproperty-alignment: \'AlignRight | AlignVCenter\';\n"
"    background: transparent;\n"
"}")
        self.labelForgotPassword.setObjectName("labelForgotPassword")
        self.horizontalLayout_ResetPwrd.addWidget(self.labelForgotPassword)
        self.buttonResetPassword = QtWidgets.QPushButton(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonResetPassword.sizePolicy().hasHeightForWidth())
        self.buttonResetPassword.setSizePolicy(sizePolicy)
        self.buttonResetPassword.setMinimumSize(QtCore.QSize(0, 30))
        self.buttonResetPassword.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonResetPassword.setStyleSheet("/* === Reset Button === */\n"
"QPushButton#buttonResetPassword {\n"
"    color: #667EEA;\n"
"    text-decoration: underline;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QPushButton#buttonResetPassword:hover {\n"
"    color: #4F63C6;\n"
"}\n"
"\n"
"QPushButton#buttonResetPassword:pressed {\n"
"    color: #3C4A99;\n"
"}")
        self.buttonResetPassword.setObjectName("buttonResetPassword")
        self.horizontalLayout_ResetPwrd.addWidget(self.buttonResetPassword)
        self.horizontalLayout_RememberReset.addLayout(self.horizontalLayout_ResetPwrd)
        self.verticalLayout_input.addLayout(self.horizontalLayout_RememberReset)
        self.gridLayout_4.addLayout(self.verticalLayout_input, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout_4.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayout_Buttons = QtWidgets.QVBoxLayout()
        self.verticalLayout_Buttons.setSpacing(10)
        self.verticalLayout_Buttons.setObjectName("verticalLayout_Buttons")
        self.labelGeneralStatus = QtWidgets.QLabel(parent=self.loginPanel)
        self.labelGeneralStatus.setStyleSheet("QLabel#labelGeneralStatus {\n"
"    font-size: 10pt;\n"
"    font-weight: bold;\n"
"    color: #555555;  /* Default text color */\n"
"    padding-top: -4px;\n"
"    padding-bottom: 2px;\n"
"    background: white;\n"
"}\n"
"\n"
"/* When property \'statusColor\' is set, override color */\n"
"QLabel#labelGeneralStatus[statusColor=\"red\"] {\n"
"    color: red;\n"
"}\n"
"QLabel#labelGeneralStatus[statusColor=\"green\"] {\n"
"    color: green;\n"
"}")
        self.labelGeneralStatus.setObjectName("labelGeneralStatus")
        self.verticalLayout_Buttons.addWidget(self.labelGeneralStatus, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.buttonLogin = QtWidgets.QPushButton(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLogin.sizePolicy().hasHeightForWidth())
        self.buttonLogin.setSizePolicy(sizePolicy)
        self.buttonLogin.setMinimumSize(QtCore.QSize(220, 45))
        self.buttonLogin.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonLogin.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonLogin.setStyleSheet("QPushButton#buttonLogin {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonLogin:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #4F63C6, stop:1 #5D3F9E);\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;\n"
"}\n"
"\n"
"QPushButton#buttonLogin:pressed {\n"
"    background: #3C4A99;\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;\n"
"}\n"
"")
        self.buttonLogin.setObjectName("buttonLogin")
        self.verticalLayout_Buttons.addWidget(self.buttonLogin, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.buttonCreateAccount = QtWidgets.QPushButton(parent=self.loginPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonCreateAccount.sizePolicy().hasHeightForWidth())
        self.buttonCreateAccount.setSizePolicy(sizePolicy)
        self.buttonCreateAccount.setMinimumSize(QtCore.QSize(220, 45))
        self.buttonCreateAccount.setMaximumSize(QtCore.QSize(16777215, 55))
        self.buttonCreateAccount.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonCreateAccount.setTabletTracking(False)
        self.buttonCreateAccount.setStyleSheet("QPushButton#buttonCreateAccount {\n"
"    background: white;\n"
"    color: #667EEA;\n"
"    border: 2px solid #667EEA;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    font-size: 12pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:hover {\n"
"    background: #f0f2ff;       /* light purple/blue tint */\n"
"    padding-top: 8px;\n"
"    padding-bottom: 12px;       /* 3D lift effect */\n"
"}\n"
"\n"
"QPushButton#buttonCreateAccount:pressed {\n"
"    background: #e0e4ff;       /* darker when pressed */\n"
"    padding-top: 12px;\n"
"    padding-bottom: 8px;       /* pressed down effect */\n"
"}\n"
"")
        self.buttonCreateAccount.setObjectName("buttonCreateAccount")
        self.verticalLayout_Buttons.addWidget(self.buttonCreateAccount, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout_4.addLayout(self.verticalLayout_Buttons, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.loginPanel, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)

        self.retranslateUi(LoginWidget)
        QtCore.QMetaObject.connectSlotsByName(LoginWidget)

    def retranslateUi(self, LoginWidget):
        _translate = QtCore.QCoreApplication.translate
        LoginWidget.setWindowTitle(_translate("LoginWidget", "Login"))
        self.logoIcon.setText(_translate("LoginWidget", "🎓"))
        self.lableTitle.setText(_translate("LoginWidget", "Welcome Back"))
        self.labelSubtitle.setText(_translate("LoginWidget", "ECE Course Registration System"))
        self.labelUsername.setText(_translate("LoginWidget", "Username (ID) or email"))
        self.lineEditUsername.setPlaceholderText(_translate("LoginWidget", "Enter username or email"))
        self.labelPassword.setText(_translate("LoginWidget", "Password"))
        self.lineEditPassword.setPlaceholderText(_translate("LoginWidget", "Enter password"))
        self.labelRemember.setText(_translate("LoginWidget", "Remember me"))
        self.labelForgotPassword.setText(_translate("LoginWidget", "Forgot Password? "))
        self.buttonResetPassword.setText(_translate("LoginWidget", "Reset here"))
        self.labelGeneralStatus.setText(_translate("LoginWidget", "General Status"))
        self.buttonLogin.setText(_translate("LoginWidget", "Sign In"))
        self.buttonCreateAccount.setText(_translate("LoginWidget", "Create Account"))
