# Form implementation generated from reading ui file 'current_schedule.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CurrentSchedule(object):
    def setupUi(self, CurrentSchedule):
        CurrentSchedule.setObjectName("CurrentSchedule")
        CurrentSchedule.resize(1200, 809)
        CurrentSchedule.setWindowTitle("")
        CurrentSchedule.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(CurrentSchedule)
        self.mainLayout.setContentsMargins(40, 40, 40, 20)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=CurrentSchedule)
        self.labelTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.headerLayout)
        self.filterFrame = QtWidgets.QFrame(parent=CurrentSchedule)
        self.filterFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.filterFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.filterFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.filterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filterFrame.setObjectName("filterFrame")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterFrame)
        self.filterLayout.setContentsMargins(25, 15, 25, 15)
        self.filterLayout.setObjectName("filterLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.buttonRefresh = QtWidgets.QPushButton(parent=self.filterFrame)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRefresh.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;     /* light grey background */\n"
"    color: #5a6c7d;               /* text color */\n"
"    border: 2px solid #e0e0e0;    /* default border */\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #6c5ce7;        /* purplish-blue border on hover */\n"
"    color: #6c5ce7;               /* match text color to border */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;    /* slightly darker grey when pressed */\n"
"    border-color: #6c5ce7;        /* keep border highlight */\n"
"    color: #6c5ce7;               /* text color */\n"
"}\n"
"")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.filterLayout.addWidget(self.buttonRefresh)
        self.mainLayout.addWidget(self.filterFrame)
        self.tableFrame = QtWidgets.QFrame(parent=CurrentSchedule)
        self.tableFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.tableMainLayout = QtWidgets.QVBoxLayout(self.tableFrame)
        self.tableMainLayout.setContentsMargins(0, 0, 0, 0)
        self.tableMainLayout.setSpacing(0)
        self.tableMainLayout.setObjectName("tableMainLayout")
        self.tableHeader = QtWidgets.QFrame(parent=self.tableFrame)
        self.tableHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.tableHeader.setMaximumSize(QtCore.QSize(16777215, 60))
        self.tableHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.tableHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableHeader.setObjectName("tableHeader")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout(self.tableHeader)
        self.tableHeaderLayout.setContentsMargins(25, 15, 25, 15)
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.tableTitle = QtWidgets.QLabel(parent=self.tableHeader)
        self.tableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.tableTitle.setObjectName("tableTitle")
        self.tableHeaderLayout.addWidget(self.tableTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem2)
        self.buttonRemoveSelected = QtWidgets.QPushButton(parent=self.tableHeader)
        self.buttonRemoveSelected.setEnabled(False)
        self.buttonRemoveSelected.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonRemoveSelected.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRemoveSelected.setStyleSheet("/* ---- Reject Button ---- */\n"
"QPushButton {\n"
"    background-color: #f8d7da;\n"
"    color: #721c24;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c82333;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #a71d2a;  /* slightly darker for pressed feedback */\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #d7bcbc; /* more washed-out red */\n"
"    color: #5e3b3e;\n"
"}")
        self.buttonRemoveSelected.setObjectName("buttonRemoveSelected")
        self.tableHeaderLayout.addWidget(self.buttonRemoveSelected)
        self.tableMainLayout.addWidget(self.tableHeader)
        self.tableCourses = QtWidgets.QTableWidget(parent=self.tableFrame)
        self.tableCourses.setMinimumSize(QtCore.QSize(0, 300))
        self.tableCourses.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #e5e5e5;      /* slightly darker for visibility */\n"
"    color: #222222;               /* matches QLineEdit text color */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 14px;\n"
"    border: none;\n"
"    color: #222222;               /* consistent text color */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #fcebed;  /* soft pink selection */\n"
"    color: #222222;             /* keep text readable */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 12px;\n"
"    border: 1px solid #c1c1c1; \n"
"    font-size: 13px;\n"
"    color: #555555;               /* similar to readOnly QLineEdit text */\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"/* Removes weird selection rectangle */\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"QTableWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QTableWidget::indicator:unchecked {\n"
"    border: 1px solid #b8b8b8;      /* soft grey border */\n"
"    background-color: #f8f8f8;      /* very light grey */\n"
"    border-radius: 3px;             /* slightly rounded */\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    border: 1px solid #5a5a5a;      /* darker grey when selected */\n"
"    background-color: #6c6c6c;      /* washed-out grey instead of harsh green */\n"
"    image: url(\"\");                 /* remove default checkmark */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked:hover,\n"
"QTableWidget::indicator:unchecked:hover {\n"
"    border-color: #3a3a3a;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked::after {\n"
"    content: \"\";\n"
"    image: url(\"\"); /* no default checkmark */\n"
"}\n"
"/* ===== SCROLLBARS (VERTICAL & HORIZONTAL) ===== */\n"
"\n"
"/* Track */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    border-radius: 6px;\n"
"    margin: 0px;  /* remove extra space */\n"
"}\n"
"\n"
"/* Handle / Thumb */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"    min-height: 30px; /* vertical */\n"
"    min-width: 30px;  /* horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Buttons (up/down or left/right) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 16px;  /* horizontal buttons width */\n"
"    height: 16px; /* vertical buttons height */\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove blank areas */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Sizes */\n"
"QScrollBar:vertical { width: 12px; }\n"
"QScrollBar:horizontal { height: 12px; }\n"
"")
        self.tableCourses.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableCourses.setAlternatingRowColors(True)
        self.tableCourses.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableCourses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableCourses.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableCourses.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableCourses.setCornerButtonEnabled(True)
        self.tableCourses.setObjectName("tableCourses")
        self.tableCourses.setColumnCount(9)
        self.tableCourses.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(8, item)
        self.tableCourses.horizontalHeader().setStretchLastSection(True)
        self.tableCourses.verticalHeader().setVisible(False)
        self.tableCourses.verticalHeader().setCascadingSectionResizes(True)
        self.tableMainLayout.addWidget(self.tableCourses)
        self.mainLayout.addWidget(self.tableFrame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(CurrentSchedule)
        QtCore.QMetaObject.connectSlotsByName(CurrentSchedule)

    def retranslateUi(self, CurrentSchedule):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("CurrentSchedule", "📅Current Schedule"))
        self.buttonRefresh.setText(_translate("CurrentSchedule", "🔄 Refresh"))
        self.tableTitle.setText(_translate("CurrentSchedule", "Current Courses registred"))
        self.buttonRemoveSelected.setText(_translate("CurrentSchedule", "❌ Remove Selected"))
        self.tableCourses.setSortingEnabled(True)
        item = self.tableCourses.horizontalHeaderItem(0)
        item.setText(_translate("CurrentSchedule", "SELECT"))
        item = self.tableCourses.horizontalHeaderItem(1)
        item.setText(_translate("CurrentSchedule", "#"))
        item = self.tableCourses.horizontalHeaderItem(2)
        item.setText(_translate("CurrentSchedule", "COURSE ID"))
        item = self.tableCourses.horizontalHeaderItem(3)
        item.setText(_translate("CurrentSchedule", "CREDIT"))
        item = self.tableCourses.horizontalHeaderItem(4)
        item.setText(_translate("CurrentSchedule", "SECTION"))
        item = self.tableCourses.horizontalHeaderItem(5)
        item.setText(_translate("CurrentSchedule", "DAYS"))
        item = self.tableCourses.horizontalHeaderItem(6)
        item.setText(_translate("CurrentSchedule", "TIME"))
        item = self.tableCourses.horizontalHeaderItem(7)
        item.setText(_translate("CurrentSchedule", "ROOM"))
        item = self.tableCourses.horizontalHeaderItem(8)
        item.setText(_translate("CurrentSchedule", "INSTRUCTOR"))
