# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Profile(object):
    def setupUi(self, Profile):
        Profile.setObjectName("Profile")
        Profile.resize(863, 900)
        Profile.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(Profile)
        self.mainLayout.setContentsMargins(40, 40, 40, 40)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.titleLabel = QtWidgets.QLabel(parent=Profile)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        self.titleLabel.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.titleLabel.setObjectName("titleLabel")
        self.mainLayout.addWidget(self.titleLabel)
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.totalUsersFrame = QtWidgets.QFrame(parent=Profile)
        self.totalUsersFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.totalUsersFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.totalUsersFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #667eea;")
        self.totalUsersFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalUsersFrame.setObjectName("totalUsersFrame")
        self.totalUsersLayout = QtWidgets.QVBoxLayout(self.totalUsersFrame)
        self.totalUsersLayout.setContentsMargins(24, 24, 24, 24)
        self.totalUsersLayout.setSpacing(12)
        self.totalUsersLayout.setObjectName("totalUsersLayout")
        self.totalUsersIcon = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.totalUsersIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon.setStyleSheet("background-color: #e8eaf6; border-radius: 10px; font-size: 24px;")
        self.totalUsersIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalUsersIcon.setObjectName("totalUsersIcon")
        self.totalUsersLayout.addWidget(self.totalUsersIcon)
        self.labelGpaCount = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.labelGpaCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelGpaCount.setObjectName("labelGpaCount")
        self.totalUsersLayout.addWidget(self.labelGpaCount)
        self.labelGpa = QtWidgets.QLabel(parent=self.totalUsersFrame)
        self.labelGpa.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelGpa.setObjectName("labelGpa")
        self.totalUsersLayout.addWidget(self.labelGpa)
        self.statsLayout.addWidget(self.totalUsersFrame)
        self.pendingRequestsFrame_2 = QtWidgets.QFrame(parent=Profile)
        self.pendingRequestsFrame_2.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame_2.setMaximumSize(QtCore.QSize(180, 200))
        self.pendingRequestsFrame_2.setStyleSheet("background-color: white;\n"
"border-radius: 12px;\n"
"border-top: 4px solid #f5576c;  /* same color as Edit Profile button */\n"
"")
        self.pendingRequestsFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame_2.setObjectName("pendingRequestsFrame_2")
        self.pendingRequestsLayout_2 = QtWidgets.QVBoxLayout(self.pendingRequestsFrame_2)
        self.pendingRequestsLayout_2.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout_2.setSpacing(12)
        self.pendingRequestsLayout_2.setObjectName("pendingRequestsLayout_2")
        self.pendingRequestsIcon_2 = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.pendingRequestsIcon_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setStyleSheet("background-color: #fff3e0; border-radius: 10px; font-size: 24px;")
        self.pendingRequestsIcon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pendingRequestsIcon_2.setObjectName("pendingRequestsIcon_2")
        self.pendingRequestsLayout_2.addWidget(self.pendingRequestsIcon_2)
        self.labelCompletedCreditsCount = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.labelCompletedCreditsCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelCompletedCreditsCount.setObjectName("labelCompletedCreditsCount")
        self.pendingRequestsLayout_2.addWidget(self.labelCompletedCreditsCount)
        self.labelCompletedCredits = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.labelCompletedCredits.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelCompletedCredits.setObjectName("labelCompletedCredits")
        self.pendingRequestsLayout_2.addWidget(self.labelCompletedCredits)
        self.statsLayout.addWidget(self.pendingRequestsFrame_2)
        self.totalStudentsFrame = QtWidgets.QFrame(parent=Profile)
        self.totalStudentsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.totalStudentsFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.totalStudentsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #f093fb;")
        self.totalStudentsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalStudentsFrame.setObjectName("totalStudentsFrame")
        self.totalStudentsLayout = QtWidgets.QVBoxLayout(self.totalStudentsFrame)
        self.totalStudentsLayout.setContentsMargins(24, 24, 24, 24)
        self.totalStudentsLayout.setSpacing(12)
        self.totalStudentsLayout.setObjectName("totalStudentsLayout")
        self.totalStudentsIcon = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.totalStudentsIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setStyleSheet("background-color: #fce4ec; border-radius: 10px; font-size: 24px;")
        self.totalStudentsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalStudentsIcon.setObjectName("totalStudentsIcon")
        self.totalStudentsLayout.addWidget(self.totalStudentsIcon)
        self.labelCurrentCreditsCount = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.labelCurrentCreditsCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelCurrentCreditsCount.setObjectName("labelCurrentCreditsCount")
        self.totalStudentsLayout.addWidget(self.labelCurrentCreditsCount)
        self.labelCurrentCredits = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.labelCurrentCredits.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelCurrentCredits.setObjectName("labelCurrentCredits")
        self.totalStudentsLayout.addWidget(self.labelCurrentCredits)
        self.statsLayout.addWidget(self.totalStudentsFrame)
        self.pendingRequestsFrame = QtWidgets.QFrame(parent=Profile)
        self.pendingRequestsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.pendingRequestsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #ffa647;")
        self.pendingRequestsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame.setObjectName("pendingRequestsFrame")
        self.pendingRequestsLayout = QtWidgets.QVBoxLayout(self.pendingRequestsFrame)
        self.pendingRequestsLayout.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout.setSpacing(12)
        self.pendingRequestsLayout.setObjectName("pendingRequestsLayout")
        self.pendingRequestsIcon = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.pendingRequestsIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon.setStyleSheet("background-color: #fff3e0; border-radius: 10px; font-size: 24px;")
        self.pendingRequestsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pendingRequestsIcon.setObjectName("pendingRequestsIcon")
        self.pendingRequestsLayout.addWidget(self.pendingRequestsIcon)
        self.labelRegisteredCoursesCount = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelRegisteredCoursesCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelRegisteredCoursesCount.setObjectName("labelRegisteredCoursesCount")
        self.pendingRequestsLayout.addWidget(self.labelRegisteredCoursesCount)
        self.labelRegisteredCourses = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelRegisteredCourses.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelRegisteredCourses.setObjectName("labelRegisteredCourses")
        self.pendingRequestsLayout.addWidget(self.labelRegisteredCourses)
        self.statsLayout.addWidget(self.pendingRequestsFrame)
        self.mainLayout.addLayout(self.statsLayout)
        self.adminInfoFrame = QtWidgets.QFrame(parent=Profile)
        self.adminInfoFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.adminInfoFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.adminInfoFrame.setObjectName("adminInfoFrame")
        self.adminInfoMainLayout = QtWidgets.QVBoxLayout(self.adminInfoFrame)
        self.adminInfoMainLayout.setContentsMargins(0, 0, 0, 0)
        self.adminInfoMainLayout.setSpacing(0)
        self.adminInfoMainLayout.setObjectName("adminInfoMainLayout")
        self.adminInfoHeader = QtWidgets.QFrame(parent=self.adminInfoFrame)
        self.adminInfoHeader.setMinimumSize(QtCore.QSize(0, 70))
        self.adminInfoHeader.setMaximumSize(QtCore.QSize(16777215, 70))
        self.adminInfoHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.adminInfoHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.adminInfoHeader.setObjectName("adminInfoHeader")
        self.adminInfoHeaderLayout = QtWidgets.QHBoxLayout(self.adminInfoHeader)
        self.adminInfoHeaderLayout.setContentsMargins(30, 20, 30, 20)
        self.adminInfoHeaderLayout.setObjectName("adminInfoHeaderLayout")
        self.labelTitleInfo = QtWidgets.QLabel(parent=self.adminInfoHeader)
        self.labelTitleInfo.setStyleSheet("font-size: 20px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitleInfo.setObjectName("labelTitleInfo")
        self.adminInfoHeaderLayout.addWidget(self.labelTitleInfo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.adminInfoHeaderLayout.addItem(spacerItem)
        self.adminInfoMainLayout.addWidget(self.adminInfoHeader)
        self.adminInfoBody = QtWidgets.QWidget(parent=self.adminInfoFrame)
        self.adminInfoBody.setStyleSheet("background: transparent;")
        self.adminInfoBody.setObjectName("adminInfoBody")
        self.adminInfoBodyLayout = QtWidgets.QVBoxLayout(self.adminInfoBody)
        self.adminInfoBodyLayout.setContentsMargins(30, 30, 30, 30)
        self.adminInfoBodyLayout.setSpacing(20)
        self.adminInfoBodyLayout.setObjectName("adminInfoBodyLayout")
        self.fieldsGrid = QtWidgets.QGridLayout()
        self.fieldsGrid.setSpacing(20)
        self.fieldsGrid.setObjectName("fieldsGrid")
        self.labelUsername = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelUsername.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelUsername.setObjectName("labelUsername")
        self.fieldsGrid.addWidget(self.labelUsername, 0, 0, 1, 1)
        self.labelProgram = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelProgram.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelProgram.setObjectName("labelProgram")
        self.fieldsGrid.addWidget(self.labelProgram, 2, 1, 1, 1)
        self.lineEditName = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditName.setEnabled(True)
        self.lineEditName.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditName.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditName.setReadOnly(True)
        self.lineEditName.setObjectName("lineEditName")
        self.fieldsGrid.addWidget(self.lineEditName, 1, 0, 1, 1)
        self.labelDepatment = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelDepatment.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelDepatment.setObjectName("labelDepatment")
        self.fieldsGrid.addWidget(self.labelDepatment, 2, 0, 1, 1)
        self.lineEditProgram = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditProgram.setEnabled(True)
        self.lineEditProgram.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditProgram.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditProgram.setReadOnly(True)
        self.lineEditProgram.setObjectName("lineEditProgram")
        self.fieldsGrid.addWidget(self.lineEditProgram, 3, 1, 1, 1)
        self.labelEmail = QtWidgets.QLabel(parent=self.adminInfoBody)
        self.labelEmail.setStyleSheet("font-size: 13px; color: #718096; font-weight: bold; background: transparent;")
        self.labelEmail.setObjectName("labelEmail")
        self.fieldsGrid.addWidget(self.labelEmail, 0, 1, 1, 1)
        self.lineEditDepartment = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditDepartment.setEnabled(True)
        self.lineEditDepartment.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditDepartment.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditDepartment.setReadOnly(True)
        self.lineEditDepartment.setObjectName("lineEditDepartment")
        self.fieldsGrid.addWidget(self.lineEditDepartment, 3, 0, 1, 1)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.adminInfoBody)
        self.lineEditEmail.setEnabled(True)
        self.lineEditEmail.setMinimumSize(QtCore.QSize(0, 45))
        self.lineEditEmail.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;\n"
"    color: #222222;        /* slightly dark text */\n"
"}\n"
"/* Read-only state */\n"
"QLineEdit[readOnly=\"true\"] {\n"
"    background-color: #f0f0f0;       /* softer to indicate non-editable */\n"
"    color: #555555;                  /* slightly faded text */\n"
"}\n"
"\n"
"")
        self.lineEditEmail.setReadOnly(False)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.fieldsGrid.addWidget(self.lineEditEmail, 1, 1, 1, 1)
        self.adminInfoBodyLayout.addLayout(self.fieldsGrid)
        self.buttonsLayout = QtWidgets.QHBoxLayout()
        self.buttonsLayout.setObjectName("buttonsLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.buttonsLayout.addItem(spacerItem1)
        self.buttonEditEmail = QtWidgets.QPushButton(parent=self.adminInfoBody)
        self.buttonEditEmail.setEnabled(False)
        self.buttonEditEmail.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonEditEmail.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonEditEmail.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background 150ms;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #4F63C6, stop:1 #5D3F9E);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3C4A99;\n"
"}\n"
"\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #e0e0e0;\n"
"    color: #999999;\n"
"}\n"
"")
        self.buttonEditEmail.setObjectName("buttonEditEmail")
        self.buttonsLayout.addWidget(self.buttonEditEmail)
        self.adminInfoBodyLayout.addLayout(self.buttonsLayout)
        self.adminInfoMainLayout.addWidget(self.adminInfoBody)
        self.mainLayout.addWidget(self.adminInfoFrame)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem2)

        self.retranslateUi(Profile)
        QtCore.QMetaObject.connectSlotsByName(Profile)

    def retranslateUi(self, Profile):
        _translate = QtCore.QCoreApplication.translate
        Profile.setWindowTitle(_translate("Profile", "Overview"))
        self.titleLabel.setText(_translate("Profile", "Profile Overview"))
        self.totalUsersIcon.setText(_translate("Profile", "⭐"))
        self.labelGpaCount.setText(_translate("Profile", "-"))
        self.labelGpa.setText(_translate("Profile", "GPA"))
        self.pendingRequestsIcon_2.setText(_translate("Profile", "🎯"))
        self.labelCompletedCreditsCount.setText(_translate("Profile", "-"))
        self.labelCompletedCredits.setText(_translate("Profile", "Completed Credits"))
        self.totalStudentsIcon.setText(_translate("Profile", "📝"))
        self.labelCurrentCreditsCount.setText(_translate("Profile", "-"))
        self.labelCurrentCredits.setText(_translate("Profile", "Current Credits"))
        self.pendingRequestsIcon.setText(_translate("Profile", "📚"))
        self.labelRegisteredCoursesCount.setText(_translate("Profile", "-"))
        self.labelRegisteredCourses.setText(_translate("Profile", "Registered Courses"))
        self.labelTitleInfo.setText(_translate("Profile", "Student Information"))
        self.labelUsername.setText(_translate("Profile", "Username"))
        self.labelProgram.setText(_translate("Profile", "Program"))
        self.lineEditName.setText(_translate("Profile", "student_user"))
        self.labelDepatment.setText(_translate("Profile", "Department"))
        self.lineEditProgram.setText(_translate("Profile", "Electrical and Computer Engineering"))
        self.labelEmail.setText(_translate("Profile", "Email Address"))
        self.lineEditDepartment.setText(_translate("Profile", "Electrical and Computer Engineering"))
        self.lineEditEmail.setText(_translate("Profile", "student@university.edu"))
        self.buttonEditEmail.setText(_translate("Profile", "Edit Email"))
