# Form implementation generated from reading ui file 'register_courses.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterCourses(object):
    def setupUi(self, RegisterCourses):
        RegisterCourses.setObjectName("RegisterCourses")
        RegisterCourses.resize(1200, 858)
        RegisterCourses.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(RegisterCourses)
        self.mainLayout.setContentsMargins(40, 40, 40, 20)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=RegisterCourses)
        self.labelTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.headerLayout)
        self.filterFrame = QtWidgets.QFrame(parent=RegisterCourses)
        self.filterFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.filterFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.filterFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.filterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filterFrame.setObjectName("filterFrame")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterFrame)
        self.filterLayout.setContentsMargins(25, 15, 25, 15)
        self.filterLayout.setObjectName("filterLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.filterFrame)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;   /* light neutral background */\n"
"    color: #5a6c7d;             /* text color similar to buttons */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #f5576c;       /* accent border on focus */\n"
"    background-color: #ffffff;   /* slightly lighter when active */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #ededed;   /* washed-out grey */\n"
"    color: #a1a8b3;             /* faded text */\n"
"}\n"
"")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.filterLayout.addWidget(self.lineEditSearch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.buttonRefresh = QtWidgets.QPushButton(parent=self.filterFrame)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRefresh.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;     /* light grey background */\n"
"    color: #5a6c7d;               /* text color */\n"
"    border: 2px solid #e0e0e0;    /* default border */\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #6c5ce7;        /* purplish-blue border on hover */\n"
"    color: #6c5ce7;               /* match text color to border */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;    /* slightly darker grey when pressed */\n"
"    border-color: #6c5ce7;        /* keep border highlight */\n"
"    color: #6c5ce7;               /* text color */\n"
"}\n"
"")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.filterLayout.addWidget(self.buttonRefresh)
        self.mainLayout.addWidget(self.filterFrame)
        self.Info = QtWidgets.QVBoxLayout()
        self.Info.setContentsMargins(-1, -1, 0, -1)
        self.Info.setSpacing(0)
        self.Info.setObjectName("Info")
        self.labelStatus_2 = QtWidgets.QLabel(parent=RegisterCourses)
        self.labelStatus_2.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelStatus_2.setObjectName("labelStatus_2")
        self.Info.addWidget(self.labelStatus_2)
        self.labelInfo_2 = QtWidgets.QLabel(parent=RegisterCourses)
        self.labelInfo_2.setStyleSheet("font-size: 12px; color: #7f8c8d; background: transparent; padding: 10px;")
        self.labelInfo_2.setWordWrap(True)
        self.labelInfo_2.setObjectName("labelInfo_2")
        self.Info.addWidget(self.labelInfo_2)
        self.mainLayout.addLayout(self.Info)
        self.tableFrame = QtWidgets.QFrame(parent=RegisterCourses)
        self.tableFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.tableMainLayout = QtWidgets.QVBoxLayout(self.tableFrame)
        self.tableMainLayout.setContentsMargins(0, 0, 0, 0)
        self.tableMainLayout.setSpacing(0)
        self.tableMainLayout.setObjectName("tableMainLayout")
        self.tableHeader = QtWidgets.QFrame(parent=self.tableFrame)
        self.tableHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.tableHeader.setMaximumSize(QtCore.QSize(16777215, 60))
        self.tableHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.tableHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableHeader.setObjectName("tableHeader")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout(self.tableHeader)
        self.tableHeaderLayout.setContentsMargins(25, 15, 25, 15)
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.tableTitle = QtWidgets.QLabel(parent=self.tableHeader)
        self.tableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.tableTitle.setObjectName("tableTitle")
        self.tableHeaderLayout.addWidget(self.tableTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem2)
        self.buttonViewSections = QtWidgets.QPushButton(parent=self.tableHeader)
        self.buttonViewSections.setEnabled(True)
        self.buttonViewSections.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonViewSections.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonViewSections.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #667EEA, stop:1 #764BA2);\n"
"    color: #ffffff;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"    transition: background 150ms;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #4F63C6, stop:1 #5D3F9E);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #3C4A99;\n"
"}\n"
"\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: #e0e0e0;\n"
"    color: #999999;\n"
"}\n"
"")
        self.buttonViewSections.setObjectName("buttonViewSections")
        self.tableHeaderLayout.addWidget(self.buttonViewSections)
        self.tableMainLayout.addWidget(self.tableHeader)
        self.tableAllCourses = QtWidgets.QTableWidget(parent=self.tableFrame)
        self.tableAllCourses.setMinimumSize(QtCore.QSize(0, 300))
        self.tableAllCourses.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #e5e5e5;      /* slightly darker for visibility */\n"
"    color: #222222;               /* matches QLineEdit text color */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 14px;\n"
"    border: none;\n"
"    color: #222222;               /* consistent text color */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #fcebed;  /* soft pink selection */\n"
"    color: #222222;             /* keep text readable */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 12px;\n"
"    border: 1px solid #c1c1c1; \n"
"    font-size: 13px;\n"
"    color: #555555;               /* similar to readOnly QLineEdit text */\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"/* Removes weird selection rectangle */\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"QTableWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QTableWidget::indicator:unchecked {\n"
"    border: 1px solid #b8b8b8;      /* soft grey border */\n"
"    background-color: #f8f8f8;      /* very light grey */\n"
"    border-radius: 3px;             /* slightly rounded */\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    border: 1px solid #5a5a5a;      /* darker grey when selected */\n"
"    background-color: #6c6c6c;      /* washed-out grey instead of harsh green */\n"
"    image: url(\"\");                 /* remove default checkmark */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked:hover,\n"
"QTableWidget::indicator:unchecked:hover {\n"
"    border-color: #3a3a3a;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked::after {\n"
"    content: \"\";\n"
"    image: url(\"\"); /* no default checkmark */\n"
"}\n"
"/* ===== SCROLLBARS (VERTICAL & HORIZONTAL) ===== */\n"
"\n"
"/* Track */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    border-radius: 6px;\n"
"    margin: 0px;  /* remove extra space */\n"
"}\n"
"\n"
"/* Handle / Thumb */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"    min-height: 30px; /* vertical */\n"
"    min-width: 30px;  /* horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Buttons (up/down or left/right) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 16px;  /* horizontal buttons width */\n"
"    height: 16px; /* vertical buttons height */\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove blank areas */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Sizes */\n"
"QScrollBar:vertical { width: 12px; }\n"
"QScrollBar:horizontal { height: 12px; }\n"
"")
        self.tableAllCourses.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableAllCourses.setAlternatingRowColors(True)
        self.tableAllCourses.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableAllCourses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableAllCourses.setCornerButtonEnabled(True)
        self.tableAllCourses.setObjectName("tableAllCourses")
        self.tableAllCourses.setColumnCount(6)
        self.tableAllCourses.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAllCourses.setHorizontalHeaderItem(5, item)
        self.tableAllCourses.horizontalHeader().setHighlightSections(True)
        self.tableAllCourses.horizontalHeader().setStretchLastSection(True)
        self.tableAllCourses.verticalHeader().setVisible(False)
        self.tableAllCourses.verticalHeader().setCascadingSectionResizes(True)
        self.tableMainLayout.addWidget(self.tableAllCourses)
        self.mainLayout.addWidget(self.tableFrame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(RegisterCourses)
        QtCore.QMetaObject.connectSlotsByName(RegisterCourses)

    def retranslateUi(self, RegisterCourses):
        _translate = QtCore.QCoreApplication.translate
        RegisterCourses.setWindowTitle(_translate("RegisterCourses", "Course"))
        self.labelTitle.setText(_translate("RegisterCourses", "Register Courses"))
        self.lineEditSearch.setPlaceholderText(_translate("RegisterCourses", "🔍  Search by Course name or code..."))
        self.buttonRefresh.setText(_translate("RegisterCourses", "🔄 Refresh"))
        self.labelStatus_2.setText(_translate("RegisterCourses", "REGISTRATION STATUS: OPEN"))
        self.labelInfo_2.setText(_translate("RegisterCourses", "ℹ️ Select prerequisites from the lists. Students must complete all prerequisites before registering for this course."))
        self.tableTitle.setText(_translate("RegisterCourses", "All Courses"))
        self.buttonViewSections.setText(_translate("RegisterCourses", " View Availabe Sections"))
        self.tableAllCourses.setSortingEnabled(True)
        item = self.tableAllCourses.horizontalHeaderItem(0)
        item.setText(_translate("RegisterCourses", "#"))
        item = self.tableAllCourses.horizontalHeaderItem(1)
        item.setText(_translate("RegisterCourses", "COURSE CODE"))
        item = self.tableAllCourses.horizontalHeaderItem(2)
        item.setText(_translate("RegisterCourses", "COURSE NAME"))
        item = self.tableAllCourses.horizontalHeaderItem(3)
        item.setText(_translate("RegisterCourses", "CREDIT HOURS"))
        item = self.tableAllCourses.horizontalHeaderItem(4)
        item.setText(_translate("RegisterCourses", "LEVEL"))
        item = self.tableAllCourses.horizontalHeaderItem(5)
        item.setText(_translate("RegisterCourses", "PREREQUISITES"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterCourses = QtWidgets.QWidget()
    ui = Ui_RegisterCourses()
    ui.setupUi(RegisterCourses)
    RegisterCourses.show()
    sys.exit(app.exec())
