# Form implementation generated from reading ui file 'transcript.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Transcript(object):
    def setupUi(self, Transcript):
        Transcript.setObjectName("Transcript")
        Transcript.resize(1200, 811)
        Transcript.setWindowTitle("")
        Transcript.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(Transcript)
        self.mainLayout.setContentsMargins(40, 40, 40, 20)
        self.mainLayout.setSpacing(30)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=Transcript)
        self.labelTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.buttonRefresh = QtWidgets.QPushButton(parent=Transcript)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRefresh.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;     /* light grey background */\n"
"    color: #5a6c7d;               /* text color */\n"
"    border: 2px solid #e0e0e0;    /* default border */\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #6c5ce7;        /* purplish-blue border on hover */\n"
"    color: #6c5ce7;               /* match text color to border */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;    /* slightly darker grey when pressed */\n"
"    border-color: #6c5ce7;        /* keep border highlight */\n"
"    color: #6c5ce7;               /* text color */\n"
"}\n"
"")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.headerLayout.addWidget(self.buttonRefresh)
        self.mainLayout.addLayout(self.headerLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=Transcript)
        self.scrollArea.setStyleSheet("\n"
"/* ===== VERTICAL SCROLLBAR ===== */\n"
"QScrollBar:vertical {\n"
"    width: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0px 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-height: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Up/Down buttons */\n"
"QScrollBar::add-line:vertical,\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical,\n"
"QScrollBar::down-arrow:vertical {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:vertical,\n"
"QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"/* ===== HORIZONTAL SCROLLBAR ===== */\n"
"QScrollBar:horizontal {\n"
"    height: 12px;\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    margin: 0px 0 0px 0;  /* TOP RIGHT BOTTOM LEFT */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    min-width: 30px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Left/Right buttons */\n"
"QScrollBar::add-line:horizontal,\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 16px;\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::left-arrow:horizontal,\n"
"QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove the blank area inside */\n"
"QScrollBar::add-page:horizontal,\n"
"QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -57, 1106, 611))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 20)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.statsLayout = QtWidgets.QHBoxLayout()
        self.statsLayout.setSpacing(20)
        self.statsLayout.setObjectName("statsLayout")
        self.totalUsersFrame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.totalUsersFrame_2.setMinimumSize(QtCore.QSize(0, 160))
        self.totalUsersFrame_2.setMaximumSize(QtCore.QSize(180, 200))
        self.totalUsersFrame_2.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #667eea;")
        self.totalUsersFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalUsersFrame_2.setObjectName("totalUsersFrame_2")
        self.totalUsersLayout_2 = QtWidgets.QVBoxLayout(self.totalUsersFrame_2)
        self.totalUsersLayout_2.setContentsMargins(24, 24, 24, 24)
        self.totalUsersLayout_2.setSpacing(12)
        self.totalUsersLayout_2.setObjectName("totalUsersLayout_2")
        self.totalUsersIcon_2 = QtWidgets.QLabel(parent=self.totalUsersFrame_2)
        self.totalUsersIcon_2.setMinimumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon_2.setMaximumSize(QtCore.QSize(50, 50))
        self.totalUsersIcon_2.setStyleSheet("background-color: #e8eaf6; border-radius: 10px; font-size: 24px;")
        self.totalUsersIcon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalUsersIcon_2.setObjectName("totalUsersIcon_2")
        self.totalUsersLayout_2.addWidget(self.totalUsersIcon_2)
        self.labelGPACount = QtWidgets.QLabel(parent=self.totalUsersFrame_2)
        self.labelGPACount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelGPACount.setObjectName("labelGPACount")
        self.totalUsersLayout_2.addWidget(self.labelGPACount)
        self.labelGPA = QtWidgets.QLabel(parent=self.totalUsersFrame_2)
        self.labelGPA.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelGPA.setObjectName("labelGPA")
        self.totalUsersLayout_2.addWidget(self.labelGPA)
        self.statsLayout.addWidget(self.totalUsersFrame_2)
        self.pendingRequestsFrame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.pendingRequestsFrame_2.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame_2.setMaximumSize(QtCore.QSize(180, 200))
        self.pendingRequestsFrame_2.setStyleSheet("background-color: white;\n"
"border-radius: 12px;\n"
"border-top: 4px solid #f5576c;  /* same color as Edit Profile button */\n"
"")
        self.pendingRequestsFrame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame_2.setObjectName("pendingRequestsFrame_2")
        self.pendingRequestsLayout_2 = QtWidgets.QVBoxLayout(self.pendingRequestsFrame_2)
        self.pendingRequestsLayout_2.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout_2.setSpacing(12)
        self.pendingRequestsLayout_2.setObjectName("pendingRequestsLayout_2")
        self.pendingRequestsIcon_2 = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.pendingRequestsIcon_2.setMinimumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setMaximumSize(QtCore.QSize(50, 50))
        self.pendingRequestsIcon_2.setStyleSheet("background-color: #fff3e0; border-radius: 10px; font-size: 24px;")
        self.pendingRequestsIcon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pendingRequestsIcon_2.setObjectName("pendingRequestsIcon_2")
        self.pendingRequestsLayout_2.addWidget(self.pendingRequestsIcon_2)
        self.labelCompletedCreditsCount = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.labelCompletedCreditsCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelCompletedCreditsCount.setObjectName("labelCompletedCreditsCount")
        self.pendingRequestsLayout_2.addWidget(self.labelCompletedCreditsCount)
        self.labelCompletedCredits = QtWidgets.QLabel(parent=self.pendingRequestsFrame_2)
        self.labelCompletedCredits.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelCompletedCredits.setObjectName("labelCompletedCredits")
        self.pendingRequestsLayout_2.addWidget(self.labelCompletedCredits)
        self.statsLayout.addWidget(self.pendingRequestsFrame_2)
        self.totalStudentsFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.totalStudentsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.totalStudentsFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.totalStudentsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #f093fb;")
        self.totalStudentsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.totalStudentsFrame.setObjectName("totalStudentsFrame")
        self.totalStudentsLayout = QtWidgets.QVBoxLayout(self.totalStudentsFrame)
        self.totalStudentsLayout.setContentsMargins(24, 24, 24, 24)
        self.totalStudentsLayout.setSpacing(12)
        self.totalStudentsLayout.setObjectName("totalStudentsLayout")
        self.totalStudentsIcon = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.totalStudentsIcon.setMinimumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setMaximumSize(QtCore.QSize(50, 50))
        self.totalStudentsIcon.setStyleSheet("background-color: #fce4ec; border-radius: 10px; font-size: 24px;")
        self.totalStudentsIcon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.totalStudentsIcon.setObjectName("totalStudentsIcon")
        self.totalStudentsLayout.addWidget(self.totalStudentsIcon)
        self.labelCurrentCreditsCount = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.labelCurrentCreditsCount.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelCurrentCreditsCount.setObjectName("labelCurrentCreditsCount")
        self.totalStudentsLayout.addWidget(self.labelCurrentCreditsCount)
        self.labelCurrentCredits = QtWidgets.QLabel(parent=self.totalStudentsFrame)
        self.labelCurrentCredits.setStyleSheet("font-size: 14px; color: #7f8c8d; background: transparent;")
        self.labelCurrentCredits.setObjectName("labelCurrentCredits")
        self.totalStudentsLayout.addWidget(self.labelCurrentCredits)
        self.statsLayout.addWidget(self.totalStudentsFrame)
        self.pendingRequestsFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.pendingRequestsFrame.setMinimumSize(QtCore.QSize(0, 160))
        self.pendingRequestsFrame.setMaximumSize(QtCore.QSize(180, 200))
        self.pendingRequestsFrame.setStyleSheet("background-color: white; border-radius: 12px; border-top: 4px solid #ffa647;")
        self.pendingRequestsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.pendingRequestsFrame.setObjectName("pendingRequestsFrame")
        self.pendingRequestsLayout = QtWidgets.QVBoxLayout(self.pendingRequestsFrame)
        self.pendingRequestsLayout.setContentsMargins(24, 24, 24, 24)
        self.pendingRequestsLayout.setSpacing(12)
        self.pendingRequestsLayout.setObjectName("pendingRequestsLayout")
        self.infoColumn2 = QtWidgets.QVBoxLayout()
        self.infoColumn2.setSpacing(5)
        self.infoColumn2.setObjectName("infoColumn2")
        self.labelMajorTitle = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelMajorTitle.setStyleSheet("font-size: 12px; color: #64748b; font-weight: 600; background: transparent;")
        self.labelMajorTitle.setObjectName("labelMajorTitle")
        self.infoColumn2.addWidget(self.labelMajorTitle)
        self.labelMajor = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelMajor.setMinimumSize(QtCore.QSize(0, 20))
        self.labelMajor.setStyleSheet("font-size: 16px; color: #1e293b; font-weight: 600; background: transparent; border: transparent")
        self.labelMajor.setObjectName("labelMajor")
        self.infoColumn2.addWidget(self.labelMajor)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.infoColumn2.addItem(spacerItem1)
        self.labelDepartmentTitle = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelDepartmentTitle.setStyleSheet("font-size: 12px; color: #64748b; font-weight: 600; background: transparent;")
        self.labelDepartmentTitle.setObjectName("labelDepartmentTitle")
        self.infoColumn2.addWidget(self.labelDepartmentTitle)
        self.labelDepartment = QtWidgets.QLabel(parent=self.pendingRequestsFrame)
        self.labelDepartment.setMinimumSize(QtCore.QSize(0, 20))
        self.labelDepartment.setStyleSheet("font-size: 16px; color: #1e293b; font-weight: 600; background: transparent; border: transparent")
        self.labelDepartment.setObjectName("labelDepartment")
        self.infoColumn2.addWidget(self.labelDepartment)
        self.pendingRequestsLayout.addLayout(self.infoColumn2)
        self.statsLayout.addWidget(self.pendingRequestsFrame)
        self.verticalLayout.addLayout(self.statsLayout)
        self.tableHeader = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.tableHeader.setMinimumSize(QtCore.QSize(0, 60))
        self.tableHeader.setMaximumSize(QtCore.QSize(16777215, 60))
        self.tableHeader.setStyleSheet("QFrame { background-color: #f8fafc; border-radius: 14px 14px 0px 0px; border-bottom: 2px solid #e2e8f0; }")
        self.tableHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableHeader.setObjectName("tableHeader")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout(self.tableHeader)
        self.tableHeaderLayout.setContentsMargins(25, 15, 25, 15)
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.labelTableTitle = QtWidgets.QLabel(parent=self.tableHeader)
        self.labelTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTableTitle.setObjectName("labelTableTitle")
        self.tableHeaderLayout.addWidget(self.labelTableTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem2)
        self.labelSemesterGPA = QtWidgets.QLabel(parent=self.tableHeader)
        self.labelSemesterGPA.setStyleSheet("font-size: 15px; font-weight: 600; color: #64748b; background: transparent;")
        self.labelSemesterGPA.setObjectName("labelSemesterGPA")
        self.tableHeaderLayout.addWidget(self.labelSemesterGPA)
        self.labelSemesterCreditsCount = QtWidgets.QLabel(parent=self.tableHeader)
        self.labelSemesterCreditsCount.setStyleSheet("font-size: 15px; font-weight: 600; color: #64748b; background: transparent; padding-left: 20px;")
        self.labelSemesterCreditsCount.setObjectName("labelSemesterCreditsCount")
        self.tableHeaderLayout.addWidget(self.labelSemesterCreditsCount)
        self.verticalLayout.addWidget(self.tableHeader)
        self.tableCourses = QtWidgets.QTableWidget(parent=self.scrollAreaWidgetContents)
        self.tableCourses.setMinimumSize(QtCore.QSize(0, 300))
        self.tableCourses.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #e5e5e5;      /* slightly darker for visibility */\n"
"    color: #222222;               /* matches QLineEdit text color */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 14px;\n"
"    border: none;\n"
"    color: #222222;               /* consistent text color */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #fcebed;  /* soft pink selection */\n"
"    color: #222222;             /* keep text readable */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 12px;\n"
"    border: 1px solid #c1c1c1; \n"
"    font-size: 13px;\n"
"    color: #555555;               /* similar to readOnly QLineEdit text */\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"/* Removes weird selection rectangle */\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"QTableWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QTableWidget::indicator:unchecked {\n"
"    border: 1px solid #b8b8b8;      /* soft grey border */\n"
"    background-color: #f8f8f8;      /* very light grey */\n"
"    border-radius: 3px;             /* slightly rounded */\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    border: 1px solid #5a5a5a;      /* darker grey when selected */\n"
"    background-color: #6c6c6c;      /* washed-out grey instead of harsh green */\n"
"    image: url(\"\");                 /* remove default checkmark */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked:hover,\n"
"QTableWidget::indicator:unchecked:hover {\n"
"    border-color: #3a3a3a;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked::after {\n"
"    content: \"\";\n"
"    image: url(\"\"); /* no default checkmark */\n"
"}\n"
"/* ===== SCROLLBARS (VERTICAL & HORIZONTAL) ===== */\n"
"\n"
"/* Track */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    border-radius: 6px;\n"
"    margin: 0px;  /* remove extra space */\n"
"}\n"
"\n"
"/* Handle / Thumb */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"    min-height: 30px; /* vertical */\n"
"    min-width: 30px;  /* horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Buttons (up/down or left/right) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 16px;  /* horizontal buttons width */\n"
"    height: 16px; /* vertical buttons height */\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove blank areas */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Sizes */\n"
"QScrollBar:vertical { width: 12px; }\n"
"QScrollBar:horizontal { height: 12px; }\n"
"")
        self.tableCourses.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableCourses.setAlternatingRowColors(True)
        self.tableCourses.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableCourses.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableCourses.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableCourses.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableCourses.setCornerButtonEnabled(True)
        self.tableCourses.setObjectName("tableCourses")
        self.tableCourses.setColumnCount(6)
        self.tableCourses.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableCourses.setHorizontalHeaderItem(5, item)
        self.tableCourses.horizontalHeader().setStretchLastSection(True)
        self.tableCourses.verticalHeader().setVisible(False)
        self.tableCourses.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.tableCourses)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        self.tableFrame = QtWidgets.QFrame(parent=Transcript)
        self.tableFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.tableFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableFrame.setObjectName("tableFrame")
        self.tableMainLayout = QtWidgets.QVBoxLayout(self.tableFrame)
        self.tableMainLayout.setContentsMargins(0, 0, 0, 0)
        self.tableMainLayout.setSpacing(0)
        self.tableMainLayout.setObjectName("tableMainLayout")
        self.mainLayout.addWidget(self.tableFrame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(Transcript)
        QtCore.QMetaObject.connectSlotsByName(Transcript)

    def retranslateUi(self, Transcript):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("Transcript", "📜 Academic Transcript"))
        self.buttonRefresh.setText(_translate("Transcript", "🔄 Refresh"))
        self.totalUsersIcon_2.setText(_translate("Transcript", "⭐"))
        self.labelGPACount.setText(_translate("Transcript", "4.67"))
        self.labelGPA.setText(_translate("Transcript", "GPA"))
        self.pendingRequestsIcon_2.setText(_translate("Transcript", "🎯"))
        self.labelCompletedCreditsCount.setText(_translate("Transcript", "15"))
        self.labelCompletedCredits.setText(_translate("Transcript", "Completed Credits"))
        self.totalStudentsIcon.setText(_translate("Transcript", "📝"))
        self.labelCurrentCreditsCount.setText(_translate("Transcript", "184"))
        self.labelCurrentCredits.setText(_translate("Transcript", "Current Credits"))
        self.labelMajorTitle.setText(_translate("Transcript", "MAJOR"))
        self.labelMajor.setText(_translate("Transcript", "POWER!!!"))
        self.labelDepartmentTitle.setText(_translate("Transcript", "DEPARTMENT"))
        self.labelDepartment.setText(_translate("Transcript", "Electrical Engineering Faculty"))
        self.labelTableTitle.setText(_translate("Transcript", "Course History"))
        self.labelSemesterGPA.setText(_translate("Transcript", "Semester GPA: 3.80"))
        self.labelSemesterCreditsCount.setText(_translate("Transcript", "Credits: 18"))
        item = self.tableCourses.horizontalHeaderItem(0)
        item.setText(_translate("Transcript", "#"))
        item = self.tableCourses.horizontalHeaderItem(1)
        item.setText(_translate("Transcript", "COURSE CODE"))
        item = self.tableCourses.horizontalHeaderItem(2)
        item.setText(_translate("Transcript", "COURSE NAME"))
        item = self.tableCourses.horizontalHeaderItem(3)
        item.setText(_translate("Transcript", "CREDIT"))
        item = self.tableCourses.horizontalHeaderItem(4)
        item.setText(_translate("Transcript", "GRADE"))
        item = self.tableCourses.horizontalHeaderItem(5)
        item.setText(_translate("Transcript", "SEMESTER"))
