# Form implementation generated from reading ui file 'view_sections.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ViewSections(object):
    def setupUi(self, ViewSections):
        ViewSections.setObjectName("ViewSections")
        ViewSections.resize(1200, 902)
        ViewSections.setStyleSheet("background-color: #f5f7fa;")
        self.mainLayout = QtWidgets.QVBoxLayout(ViewSections)
        self.mainLayout.setContentsMargins(40, 30, 40, 30)
        self.mainLayout.setSpacing(10)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setObjectName("headerLayout")
        self.labelTitle = QtWidgets.QLabel(parent=ViewSections)
        self.labelTitle.setStyleSheet("font-size: 28px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTitle.setObjectName("labelTitle")
        self.headerLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.mainLayout.addLayout(self.headerLayout)
        self.filterFrame = QtWidgets.QFrame(parent=ViewSections)
        self.filterFrame.setMinimumSize(QtCore.QSize(0, 70))
        self.filterFrame.setMaximumSize(QtCore.QSize(16777215, 70))
        self.filterFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.filterFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.filterFrame.setObjectName("filterFrame")
        self.filterLayout = QtWidgets.QHBoxLayout(self.filterFrame)
        self.filterLayout.setContentsMargins(25, 15, 25, 15)
        self.filterLayout.setObjectName("filterLayout")
        self.lineEditSearch = QtWidgets.QLineEdit(parent=self.filterFrame)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    padding: 10px 15px;\n"
"    border: 2px solid #e0e0e0;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    background-color: #f8f9fa;   /* light neutral background */\n"
"    color: #5a6c7d;             /* text color similar to buttons */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #f5576c;       /* accent border on focus */\n"
"    background-color: #ffffff;   /* slightly lighter when active */\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #ededed;   /* washed-out grey */\n"
"    color: #a1a8b3;             /* faded text */\n"
"}\n"
"")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.filterLayout.addWidget(self.lineEditSearch)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.filterLayout.addItem(spacerItem1)
        self.buttonRefresh = QtWidgets.QPushButton(parent=self.filterFrame)
        self.buttonRefresh.setMinimumSize(QtCore.QSize(100, 40))
        self.buttonRefresh.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRefresh.setStyleSheet("QPushButton {\n"
"    background-color: #f8f9fa;     /* light grey background */\n"
"    color: #5a6c7d;               /* text color */\n"
"    border: 2px solid #e0e0e0;    /* default border */\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #6c5ce7;        /* purplish-blue border on hover */\n"
"    color: #6c5ce7;               /* match text color to border */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #e0e0e0;    /* slightly darker grey when pressed */\n"
"    border-color: #6c5ce7;        /* keep border highlight */\n"
"    color: #6c5ce7;               /* text color */\n"
"}\n"
"")
        self.buttonRefresh.setObjectName("buttonRefresh")
        self.filterLayout.addWidget(self.buttonRefresh)
        self.mainLayout.addWidget(self.filterFrame)
        self.sectionsTableFrame = QtWidgets.QFrame(parent=ViewSections)
        self.sectionsTableFrame.setStyleSheet("background-color: white; border-radius: 12px;")
        self.sectionsTableFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.sectionsTableFrame.setObjectName("sectionsTableFrame")
        self.sectionsTableMainLayout = QtWidgets.QVBoxLayout(self.sectionsTableFrame)
        self.sectionsTableMainLayout.setContentsMargins(0, 0, 0, 0)
        self.sectionsTableMainLayout.setSpacing(0)
        self.sectionsTableMainLayout.setObjectName("sectionsTableMainLayout")
        self.tableHeader = QtWidgets.QFrame(parent=self.sectionsTableFrame)
        self.tableHeader.setMinimumSize(QtCore.QSize(0, 70))
        self.tableHeader.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tableHeader.setStyleSheet("background: transparent; border-bottom: 2px solid #f0f0f0;")
        self.tableHeader.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tableHeader.setObjectName("tableHeader")
        self.tableHeaderLayout = QtWidgets.QHBoxLayout(self.tableHeader)
        self.tableHeaderLayout.setContentsMargins(30, 20, 30, 20)
        self.tableHeaderLayout.setObjectName("tableHeaderLayout")
        self.labelTableTitle = QtWidgets.QLabel(parent=self.tableHeader)
        self.labelTableTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #2c3e50; background: transparent;")
        self.labelTableTitle.setObjectName("labelTableTitle")
        self.tableHeaderLayout.addWidget(self.labelTableTitle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.tableHeaderLayout.addItem(spacerItem2)
        self.comboBoxFilterCourses = QtWidgets.QComboBox(parent=self.tableHeader)
        self.comboBoxFilterCourses.setMinimumSize(QtCore.QSize(180, 40))
        self.comboBoxFilterCourses.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBoxFilterCourses.setStyleSheet("/* ----------------- QComboBox Base ----------------- */\n"
"QComboBox {\n"
"    border: 2px solid #E0E0E0;          /* main border */\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                   /* Matches QLineEdit padding */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"}\n"
"\n"
"/* Focused state */\n"
"QComboBox:focus {\n"
"    border: 2px solid #667EEA; \n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* ----------------- Drop-down Arrow ----------------- */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-width: 1px;\n"
"    border-left-color: #E0E0E0;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 12px;       /* rounder corners */\n"
"    border-bottom-right-radius: 12px;    /* rounder corners */\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove ugly black border on hover/focus */\n"
"QComboBox::drop-down:hover,\n"
"QComboBox::drop-down:focus {\n"
"    border-left-color: #667EEA;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Modern, visible arrow using simple chevron */\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: solid #667EEA;\n"
"    border-width: 0 2px 2px 0;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"/* ----------------- Dropdown Popup ----------------- */\n"
"/* Dropdown Popup */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fdfdfd;          /* slightly off-white */\n"
"    border: 2px solid #E0E0E0;          /* subtle grey border */\n"
"    border-radius: 8px;                  /* may not be perfect on Windows */\n"
"    color: #111111;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"    selection-background-color: #667EEA;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items hover/selection */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(102, 126, 234, 0.1);\n"
"    color: #111111;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #667EEA;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Error highlight for combo box */\n"
"QComboBox[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}")
        self.comboBoxFilterCourses.setEditable(True)
        self.comboBoxFilterCourses.setObjectName("comboBoxFilterCourses")
        self.comboBoxFilterCourses.addItem("")
        self.tableHeaderLayout.addWidget(self.comboBoxFilterCourses)
        self.comboBoxStatusFilter = QtWidgets.QComboBox(parent=self.tableHeader)
        self.comboBoxStatusFilter.setMinimumSize(QtCore.QSize(150, 40))
        self.comboBoxStatusFilter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.comboBoxStatusFilter.setStyleSheet("/* ----------------- QComboBox Base ----------------- */\n"
"QComboBox {\n"
"    border: 2px solid #E0E0E0;          /* main border */\n"
"    border-radius: 10px;\n"
"    padding: 8px 10px;                   /* Matches QLineEdit padding */\n"
"    background: rgba(250, 250, 250, 200);\n"
"    font-size: 11pt;\n"
"    color: #111111;\n"
"}\n"
"\n"
"/* Focused state */\n"
"QComboBox:focus {\n"
"    border: 2px solid #667EEA; \n"
"    background: rgba(250, 250, 250, 220);\n"
"}\n"
"\n"
"/* ----------------- Drop-down Arrow ----------------- */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 30px; \n"
"    border-left-width: 1px;\n"
"    border-left-color: #E0E0E0;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 12px;       /* rounder corners */\n"
"    border-bottom-right-radius: 12px;    /* rounder corners */\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove ugly black border on hover/focus */\n"
"QComboBox::drop-down:hover,\n"
"QComboBox::drop-down:focus {\n"
"    border-left-color: #667EEA;\n"
"    background: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"/* Modern, visible arrow using simple chevron */\n"
"QComboBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    border: solid #667EEA;\n"
"    border-width: 0 2px 2px 0;\n"
"    margin-right: 6px;\n"
"}\n"
"\n"
"/* ----------------- Dropdown Popup ----------------- */\n"
"/* Dropdown Popup */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #fdfdfd;          /* slightly off-white */\n"
"    border: 2px solid #E0E0E0;          /* subtle grey border */\n"
"    border-radius: 8px;                  /* may not be perfect on Windows */\n"
"    color: #111111;\n"
"    font-size: 11pt;\n"
"    padding: 5px;\n"
"    selection-background-color: #667EEA;\n"
"    selection-color: white;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Items hover/selection */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(102, 126, 234, 0.1);\n"
"    color: #111111;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: #667EEA;\n"
"    color: white;\n"
"}\n"
"\n"
"/* Error highlight for combo box */\n"
"QComboBox[error=\"true\"] {\n"
"    border: 2px solid #FF4A4A;\n"
"}")
        self.comboBoxStatusFilter.setObjectName("comboBoxStatusFilter")
        self.comboBoxStatusFilter.addItem("")
        self.comboBoxStatusFilter.addItem("")
        self.comboBoxStatusFilter.addItem("")
        self.comboBoxStatusFilter.addItem("")
        self.tableHeaderLayout.addWidget(self.comboBoxStatusFilter)
        self.buttonRegisterCourse = QtWidgets.QPushButton(parent=self.tableHeader)
        self.buttonRegisterCourse.setEnabled(True)
        self.buttonRegisterCourse.setMinimumSize(QtCore.QSize(120, 40))
        self.buttonRegisterCourse.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.buttonRegisterCourse.setStyleSheet("/* ---- Approve Button ---- */\n"
"QPushButton {\n"
"    background-color: #d4edda;\n"
"    color: #155724;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    padding: 10px 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #28a745;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #1e7e34;  /* slightly darker for pressed feedback */\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: #c1d9c3; /* more washed-out green */\n"
"    color: #7a8b7a;\n"
"}")
        self.buttonRegisterCourse.setObjectName("buttonRegisterCourse")
        self.tableHeaderLayout.addWidget(self.buttonRegisterCourse)
        self.sectionsTableMainLayout.addWidget(self.tableHeader)
        self.tableSections = QtWidgets.QTableWidget(parent=self.sectionsTableFrame)
        self.tableSections.setMinimumSize(QtCore.QSize(0, 300))
        self.tableSections.setStyleSheet("QTableWidget {\n"
"    border: none;\n"
"    background-color: white;\n"
"    gridline-color: #e5e5e5;      /* slightly darker for visibility */\n"
"    color: #222222;               /* matches QLineEdit text color */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 14px;\n"
"    border: none;\n"
"    color: #222222;               /* consistent text color */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #fcebed;  /* soft pink selection */\n"
"    color: #222222;             /* keep text readable */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f8f9fa;\n"
"    padding: 12px;\n"
"    border: 1px solid #c1c1c1; \n"
"    font-size: 13px;\n"
"    color: #555555;               /* similar to readOnly QLineEdit text */\n"
"    font-weight: bold;\n"
"}\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"/* Removes weird selection rectangle */\n"
"QTableWidget::item:focus {\n"
"    outline: none;\n"
"    border: none;\n"
"}\n"
"QTableWidget::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"}\n"
"\n"
"QTableWidget::indicator:unchecked {\n"
"    border: 1px solid #b8b8b8;      /* soft grey border */\n"
"    background-color: #f8f8f8;      /* very light grey */\n"
"    border-radius: 3px;             /* slightly rounded */\n"
"}\n"
"\n"
"QTableWidget::indicator:checked {\n"
"    border: 1px solid #5a5a5a;      /* darker grey when selected */\n"
"    background-color: #6c6c6c;      /* washed-out grey instead of harsh green */\n"
"    image: url(\"\");                 /* remove default checkmark */\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked:hover,\n"
"QTableWidget::indicator:unchecked:hover {\n"
"    border-color: #3a3a3a;\n"
"}\n"
"\n"
"QTableWidget::indicator:checked::after {\n"
"    content: \"\";\n"
"    image: url(\"\"); /* no default checkmark */\n"
"}\n"
"\n"
"/* ===== SCROLLBARS (VERTICAL & HORIZONTAL) ===== */\n"
"\n"
"/* Track */\n"
"QScrollBar:vertical, QScrollBar:horizontal {\n"
"    background: rgba(255, 255, 255, 0.05);  /* subtle track */\n"
"    border-radius: 6px;\n"
"    margin: 0px;  /* remove extra space */\n"
"}\n"
"\n"
"/* Handle / Thumb */\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: rgba(120, 120, 120, 0.35);  /* glassy thumb */\n"
"    border-radius: 6px;\n"
"    border: 1px solid rgba(255, 255, 255, 0.2); /* subtle highlight */\n"
"    min-height: 30px; /* vertical */\n"
"    min-width: 30px;  /* horizontal */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover,\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: rgba(120, 120, 120, 0.55);\n"
"}\n"
"\n"
"/* Buttons (up/down or left/right) */\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,\n"
"QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
"    width: 16px;  /* horizontal buttons width */\n"
"    height: 16px; /* vertical buttons height */\n"
"    background: rgba(180, 180, 180, 0.35);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrow icons */\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical,\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width: 6px;\n"
"    height: 6px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Remove blank areas */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"/* Sizes */\n"
"QScrollBar:vertical { width: 12px; }\n"
"QScrollBar:horizontal { height: 12px; }\n"
"")
        self.tableSections.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableSections.setAlternatingRowColors(True)
        self.tableSections.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.tableSections.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableSections.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tableSections.setCornerButtonEnabled(True)
        self.tableSections.setObjectName("tableSections")
        self.tableSections.setColumnCount(9)
        self.tableSections.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSections.setHorizontalHeaderItem(8, item)
        self.tableSections.horizontalHeader().setStretchLastSection(True)
        self.tableSections.verticalHeader().setVisible(False)
        self.tableSections.verticalHeader().setCascadingSectionResizes(True)
        self.sectionsTableMainLayout.addWidget(self.tableSections)
        self.mainLayout.addWidget(self.sectionsTableFrame)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.mainLayout.addItem(spacerItem3)

        self.retranslateUi(ViewSections)
        QtCore.QMetaObject.connectSlotsByName(ViewSections)

    def retranslateUi(self, ViewSections):
        _translate = QtCore.QCoreApplication.translate
        ViewSections.setWindowTitle(_translate("ViewSections", "Avaliable Sections"))
        self.labelTitle.setText(_translate("ViewSections", "Available Course Sections"))
        self.lineEditSearch.setPlaceholderText(_translate("ViewSections", "🔍  Search Sections by ID..."))
        self.buttonRefresh.setText(_translate("ViewSections", "🔄 Refresh"))
        self.labelTableTitle.setText(_translate("ViewSections", "All Course Sections"))
        self.comboBoxFilterCourses.setItemText(0, _translate("ViewSections", "All Courses"))
        self.comboBoxStatusFilter.setItemText(0, _translate("ViewSections", "All Status"))
        self.comboBoxStatusFilter.setItemText(1, _translate("ViewSections", "Open"))
        self.comboBoxStatusFilter.setItemText(2, _translate("ViewSections", "Closed"))
        self.comboBoxStatusFilter.setItemText(3, _translate("ViewSections", "Full"))
        self.buttonRegisterCourse.setText(_translate("ViewSections", "Register Course"))
        item = self.tableSections.horizontalHeaderItem(0)
        item.setText(_translate("ViewSections", "#"))
        item = self.tableSections.horizontalHeaderItem(1)
        item.setText(_translate("ViewSections", "ID"))
        item = self.tableSections.horizontalHeaderItem(2)
        item.setText(_translate("ViewSections", "COURSE"))
        item = self.tableSections.horizontalHeaderItem(3)
        item.setText(_translate("ViewSections", "INSTRUCTOR"))
        item = self.tableSections.horizontalHeaderItem(4)
        item.setText(_translate("ViewSections", "SCHEDULE"))
        item = self.tableSections.horizontalHeaderItem(5)
        item.setText(_translate("ViewSections", "ENROLLED"))
        item = self.tableSections.horizontalHeaderItem(6)
        item.setText(_translate("ViewSections", "CAPACITY"))
        item = self.tableSections.horizontalHeaderItem(7)
        item.setText(_translate("ViewSections", "STATUS"))
        item = self.tableSections.horizontalHeaderItem(8)
        item.setText(_translate("ViewSections", "REGISTERATION"))
